// ==========================================================
// คลังคำศัพท์ English B1
// ==========================================================
window.flashVocabDataEnB1 = [
{ word:"absolutely", meaning:"แน่นอน, อย่างยิ่ง" },
{ word:"academic", meaning:"วิชาการ" },
{ word:"access", meaning:"เข้าถึง, ทางเข้า" },
{ word:"accommodation", meaning:"ที่พัก" },
{ word:"account", meaning:"บัญชี" },
{ word:"achievement", meaning:"ความสำเร็จ" },
{ word:"act", meaning:"แสดง, การกระทำ" },
{ word:"ad", meaning:"โฆษณา" },
{ word:"addition", meaning:"การเพิ่ม, บวก" },
{ word:"admire", meaning:"ชื่นชม, เลื่อมใส" },
{ word:"admit", meaning:"ยอมรับ" },
{ word:"advanced", meaning:"ขั้นสูง" },
{ word:"advise", meaning:"แนะนำ" },
{ word:"afford", meaning:"จ่ายไหว, มีเงินพอ" },
{ word:"age", meaning:"อายุ" },
{ word:"aged", meaning:"มีอายุ, วัย" },
{ word:"agent", meaning:"ตัวแทน" },
{ word:"agreement", meaning:"ข้อตกลง, ความเห็นพ้อง" },
{ word:"ahead", meaning:"ข้างหน้า, ล่วงหน้า" },
{ word:"aim", meaning:"เป้าหมาย, เล็ง" },
{ word:"alarm", meaning:"สัญญาณเตือน, ปลุก" },
{ word:"album", meaning:"อัลบั้ม" },
{ word:"alcohol", meaning:"แอลกอฮอล์" },
{ word:"alcoholic", meaning:"ซึ่งมีแอลกอฮอล์" },
{ word:"alternative", meaning:"ทางเลือก" },
{ word:"amazed", meaning:"ทึ่ง, ประหลาดใจ" },
{ word:"ambition", meaning:"ความทะเยอทะยาน" },
{ word:"ambitious", meaning:"ทะเยอทะยาน" },
{ word:"analyse", meaning:"วิเคราะห์" },
{ word:"analysis", meaning:"การวิเคราะห์" },
{ word:"announce", meaning:"ประกาศ" },
{ word:"announcement", meaning:"การประกาศ" },
{ word:"annoy", meaning:"รบกวน, ทำให้รำคาญ" },
{ word:"annoyed", meaning:"รำคาญ" },
{ word:"annoying", meaning:"น่ารำคาญ" },
{ word:"apart", meaning:"แยกจากกัน" },
{ word:"apologize", meaning:"ขอโทษ" },
{ word:"application", meaning:"ใบสมัคร, การประยุกต์" },
{ word:"appointment", meaning:"การนัดหมาย" },
{ word:"appreciate", meaning:"ซาบซึ้ง, เห็นคุณค่า" },
{ word:"approximately", meaning:"ประมาณ, คร่าวๆ" },
{ word:"arrest", meaning:"จับกุม" },
{ word:"arrival", meaning:"การมาถึง" },
{ word:"assignment", meaning:"งานที่ได้รับมอบหมาย" },
{ word:"assist", meaning:"ช่วยเหลือ" },
{ word:"atmosphere", meaning:"บรรยากาศ" },
{ word:"attach", meaning:"แนบ, ติด" },
{ word:"attitude", meaning:"ทัศนคติ" },
{ word:"attract", meaning:"ดึงดูด" },
{ word:"attraction", meaning:"สถานที่ท่องเที่ยว, เสน่ห์" },
{ word:"authority", meaning:"อำนาจ, เจ้าหน้าที่" },
{ word:"average", meaning:"เฉลี่ย" },
{ word:"award", meaning:"รางวัล" },
{ word:"aware", meaning:"ตระหนักรู้, รู้ตัว" },
{ word:"backwards", meaning:"ถอยหลัง" },
{ word:"bake", meaning:"อบ" },
{ word:"balance", meaning:"สมดุล, ยอดคงเหลือ" },
{ word:"ban", meaning:"ห้าม" },
{ word:"bank (river)", meaning:"ตลิ่ง, ฝั่งแม่น้ำ" },
{ word:"base", meaning:"ฐาน, รากฐาน" },
{ word:"basic", meaning:"พื้นฐาน" },
{ word:"basis", meaning:"เกณฑ์, หลักฐาน" },
{ word:"battery", meaning:"แบตเตอรี่" },
{ word:"battle", meaning:"การต่อสู้, สงคราม" },
{ word:"beauty", meaning:"ความงาม" },
{ word:"bee", meaning:"ผึ้ง" },
{ word:"belief", meaning:"ความเชื่อ" },
{ word:"bell", meaning:"กระดิ่ง, ระฆัง" },
{ word:"bend", meaning:"โค้ง, งอ" },
{ word:"benefit", meaning:"ผลประโยชน์" },
{ word:"better", meaning:"ดีกว่า" },
{ word:"bite", meaning:"กัด" },
{ word:"block", meaning:"บล็อก, กีดขวาง" },
{ word:"board", meaning:"กระดาน, คณะกรรมการ" },
{ word:"bomb", meaning:"ระเบิด" },
{ word:"border", meaning:"ชายแดน, ขอบ" },
{ word:"bother", meaning:"รบกวน, ใส่ใจ" },
{ word:"branch", meaning:"สาขา, กิ่งไม้" },
{ word:"brand", meaning:"ตราสินค้า, ยี่ห้อ" },
{ word:"brave", meaning:"กล้าหาญ" },
{ word:"breath", meaning:"ลมหายใจ" },
{ word:"breathe", meaning:"หายใจ" },
{ word:"breathing", meaning:"การหายใจ" },
{ word:"bride", meaning:"เจ้าสาว" },
{ word:"bubble", meaning:"ฟองสบู่, ฟอง" },
{ word:"bury", meaning:"ฝัง, ฝังศพ" },
{ word:"by", meaning:"โดย, ข้างๆ" },
{ word:"calm", meaning:"สงบ" },
{ word:"campaign", meaning:"การรณรงค์" },
{ word:"campus", meaning:"วิทยาเขต" },
{ word:"candidate", meaning:"ผู้สมัคร" },
{ word:"cap", meaning:"หมวกแก๊ป, ฝาครอบ" },
{ word:"captain", meaning:"กัปตัน, หัวหน้า" },
{ word:"careless", meaning:"ประมาท, เลินเล่อ" },
{ word:"category", meaning:"ประเภท, หมวดหมู่" },
{ word:"ceiling", meaning:"เพดาน" },
{ word:"celebration", meaning:"การเฉลิมฉลอง" },
{ word:"central", meaning:"ศูนย์กลาง, ส่วนกลาง" },
{ word:"centre", meaning:"ศูนย์กลาง" },
{ word:"ceremony", meaning:"พิธีการ" },
{ word:"chain", meaning:"โซ่, ห่วงโซ่" },
{ word:"challenge", meaning:"ความท้าทาย" },
{ word:"champion", meaning:"แชมป์, ผู้ชนะ" },
{ word:"channel", meaning:"ช่อง, ช่องทาง" },
{ word:"chapter", meaning:"บท" },
{ word:"charge", meaning:"คิดราคา, ชาร์จไฟ" },
{ word:"cheap", meaning:"ถูก, ราคาถูก" },
{ word:"cheat", meaning:"โกง, นอกใจ" },
{ word:"cheerful", meaning:"ร่าเริง" },
{ word:"chemical", meaning:"สารเคมี" },
{ word:"chest", meaning:"หน้าอก, หีบ" },
{ word:"childhood", meaning:"วัยเด็ก" },
{ word:"claim", meaning:"อ้าง, เรียกร้อง" },
{ word:"clause", meaning:"อนุประโยค, ข้อกำหนด" },
{ word:"clear", meaning:"ชัดเจน, เคลียร์" },
{ word:"click", meaning:"คลิก" },
{ word:"client", meaning:"ลูกค้า" },
{ word:"climb", meaning:"ปีน" },
{ word:"close2", meaning:"ใกล้" },
{ word:"cloth", meaning:"ผ้า" },
{ word:"clue", meaning:"เบาะแส" },
{ word:"coach", meaning:"โค้ช, รถบัสทางไกล" },
{ word:"coal", meaning:"ถ่านหิน" },
{ word:"coin", meaning:"เหรียญ" },
{ word:"collection", meaning:"การสะสม, ของสะสม" },
{ word:"coloured", meaning:"มีสี" },
{ word:"combine", meaning:"รวมกัน" },
{ word:"comment", meaning:"ความคิดเห็น" },
{ word:"commercial", meaning:"เชิงพาณิชย์, โฆษณา" },
{ word:"commit", meaning:"ผูกมัด, กระทำผิด" },
{ word:"communication", meaning:"การสื่อสาร" },
{ word:"comparison", meaning:"การเปรียบเทียบ" },
{ word:"competitor", meaning:"คู่แข่ง" },
{ word:"competitive", meaning:"เกี่ยวกับการแข่งขัน" },
{ word:"complaint", meaning:"การร้องเรียน" },
{ word:"complex", meaning:"ซับซ้อน" },
{ word:"concentrate", meaning:"มีสมาธิ, จดจ่อ" },
{ word:"conclude", meaning:"สรุป" },
{ word:"conclusion", meaning:"ข้อสรุป" },
{ word:"confident", meaning:"มั่นใจ" },
{ word:"confirm", meaning:"ยืนยัน" },
{ word:"confuse", meaning:"ทำให้สับสน" },
{ word:"confused", meaning:"สับสน" },
{ word:"connection", meaning:"การเชื่อมต่อ, ความสัมพันธ์" },
{ word:"consequence", meaning:"ผลลัพธ์, ผลที่ตามมา" },
{ word:"consist", meaning:"ประกอบด้วย" },
{ word:"consume", meaning:"บริโภค" },
{ word:"consumer", meaning:"ผู้บริโภค" },
{ word:"contact", meaning:"ติดต่อ" },
{ word:"container", meaning:"ตู้คอนเทนเนอร์, ภาชนะ" },
{ word:"content1", meaning:"เนื้อหา" },
{ word:"continuous", meaning:"ต่อเนื่อง" },
{ word:"contrast", meaning:"ความแตกต่าง, เปรียบเทียบ" },
{ word:"convenient", meaning:"สะดวก" },
{ word:"convince", meaning:"โน้มน้าว, ทำให้เชื่อ" },
{ word:"cool", meaning:"เย็น, เจ๋ง" },
{ word:"costume", meaning:"เครื่องแต่งกาย" },
{ word:"cottage", meaning:"กระท่อม" },
{ word:"cotton", meaning:"ฝ้าย, สำลี" },
{ word:"count", meaning:"นับ" },
{ word:"countryside", meaning:"ชนบท" },
{ word:"court", meaning:"ศาล, สนาม" },
{ word:"cover", meaning:"ปกคลุม, ปก" },
{ word:"covered", meaning:"ที่ถูกปกคลุม" },
{ word:"cream", meaning:"ครีม" },
{ word:"criminal", meaning:"อาชญากร" },
{ word:"cruel", meaning:"โหดร้าย" },
{ word:"cultural", meaning:"ทางวัฒนธรรม" },
{ word:"currency", meaning:"สกุลเงิน" },
{ word:"current", meaning:"ปัจจุบัน, กระแส" },
{ word:"currently", meaning:"ในปัจจุบัน" },
{ word:"curtain", meaning:"ม่าน" },
{ word:"custom", meaning:"ขนบธรรมเนียม" },
{ word:"cut", meaning:"ตัด" },
{ word:"daily", meaning:"รายวัน" },
{ word:"damage", meaning:"ความเสียหาย, ทำลาย" },
{ word:"deal", meaning:"จัดการ, ข้อตกลง" },
{ word:"decade", meaning:"ทศวรรษ" },
{ word:"decorate", meaning:"ตกแต่ง" },
{ word:"deep", meaning:"ลึก" },
{ word:"define", meaning:"นิยาม, กำหนด" },
{ word:"definite", meaning:"แน่นอน, ชัดเจน" },
{ word:"definition", meaning:"คำจำกัดความ" },
{ word:"deliver", meaning:"ส่ง, จัดส่ง" },
{ word:"departure", meaning:"การขาออก, การจากไป" },
{ word:"despite", meaning:"ทั้งๆ ที่" },
{ word:"destination", meaning:"จุดหมายปลายทาง" },
{ word:"determine", meaning:"กำหนด, ตัดสินใจ" },
{ word:"determined", meaning:"มุ่งมั่น" },
{ word:"development", meaning:"การพัฒนา" },
{ word:"diagram", meaning:"แผนภูมิ, แผนผัง" },
{ word:"diamond", meaning:"เพชร" },
{ word:"difficulty", meaning:"ความยากลำบาก" },
{ word:"direct", meaning:"โดยตรง, กำกับ" },
{ word:"directly", meaning:"โดยตรง" },
{ word:"dirt", meaning:"สิ่งสกปรก" },
{ word:"disadvantage", meaning:"ข้อเสียเปรียบ" },
{ word:"disconnected", meaning:"ขาดการเชื่อมต่อ" },
{ word:"disappointed", meaning:"ผิดหวัง" },
{ word:"disappointing", meaning:"น่าผิดหวัง" },
{ word:"discount", meaning:"ส่วนลด" },
{ word:"dislike", meaning:"ไม่ชอบ" },
{ word:"divide", meaning:"แบ่ง" },
{ word:"documentary", meaning:"สารคดี" },
{ word:"donate", meaning:"บริจาค" },
{ word:"double", meaning:"สองเท่า, คู่" },
{ word:"doubt", meaning:"สงสัย" },
{ word:"dressed", meaning:"แต่งกาย" },
{ word:"drop", meaning:"ตก, หล่น, หยอด" },
{ word:"drum", meaning:"กลอง" },
{ word:"drunk", meaning:"เมา" },
{ word:"due", meaning:"มีกำหนด, เนื่องจาก" },
{ word:"dust", meaning:"ฝุ่น" },
{ word:"duty", meaning:"หน้าที่, ภาษี" },
{ word:"earthquake", meaning:"แผ่นดินไหว" },
{ word:"eastern", meaning:"ทางทิศตะวันออก" },
{ word:"economic", meaning:"ทางเศรษฐกิจ" },
{ word:"economy", meaning:"เศรษฐกิจ" },
{ word:"edge", meaning:"ขอบ" },
{ word:"editor", meaning:"บรรณาธิการ" },
{ word:"educate", meaning:"ให้การศึกษา" },
{ word:"educated", meaning:"มีการศึกษา" },
{ word:"educational", meaning:"เกี่ยวกับการศึกษา" },
{ word:"effective", meaning:"มีประสิทธิภาพ" },
{ word:"effectively", meaning:"อย่างมีประสิทธิภาพ" },
{ word:"effort", meaning:"ความพยายาม" },
{ word:"election", meaning:"การเลือกตั้ง" },
{ word:"element", meaning:"องค์ประกอบ, ธาตุ" },
{ word:"embarrassed", meaning:"อับอาย, ขัดเขิน" },
{ word:"embarrassing", meaning:"น่าอับอาย" },
{ word:"emergency", meaning:"ฉุกเฉน" },
{ word:"emotion", meaning:"อารมณ์" },
{ word:"employment", meaning:"การจ้างงาน" },
{ word:"empty", meaning:"ว่างเปล่า" },
{ word:"encourage", meaning:"สนับสนุน, ให้กำลังใจ" },
{ word:"enemy", meaning:"ศัตรู" },
{ word:"engaged", meaning:"หมั้น, ไม่ว่าง" },
{ word:"engineering", meaning:"วิศวกรรมศาสตร์" },
{ word:"entertain", meaning:"ให้ความบันเทิง" },
{ word:"entertainment", meaning:"ความบันเทิง" },
{ word:"entrance", meaning:"ทางเข้า" },
{ word:"entry", meaning:"การเข้า, ผลงาน" },
{ word:"environmental", meaning:"ทางสิ่งแวดล้อม" },
{ word:"episode", meaning:"ตอน" },
{ word:"equal", meaning:"เท่ากัน" },
{ word:"equally", meaning:"อย่างเท่าเทียม" },
{ word:"escape", meaning:"หลบหนี" },
{ word:"essential", meaning:"จำเป็น, สำคัญยิ่ง" },
{ word:"eventually", meaning:"ในที่สุด" },
{ word:"examine", meaning:"ตรวจสอบ, ตรวจ" },
{ word:"except", meaning:"ยกเว้น" },
{ word:"exchange", meaning:"แลกเปลี่ยน" },
{ word:"excitement", meaning:"ความตื่นเต้น" },
{ word:"exhibition", meaning:"นิทรรศการ" },
{ word:"expand", meaning:"ขยาย" },
{ word:"expected", meaning:"ที่คาดไว้" },
{ word:"expedition", meaning:"การสำรวจ" },
{ word:"experience", meaning:"ประสบการณ์" },
{ word:"experienced", meaning:"มีประสบการณ์" },
{ word:"experiment", meaning:"การทดลอง" },
{ word:"explode", meaning:"ระเบิด" },
{ word:"explore", meaning:"สำรวจ" },
{ word:"explosion", meaning:"การระเบิด" },
{ word:"export", meaning:"ส่งออก" },
{ word:"extra", meaning:"พิเศษ, เพิ่มเติม" },
{ word:"face", meaning:"เผชิญหน้า, ใบหน้า" },
{ word:"fairly", meaning:"ค่อนข้าง, อย่างยุติธรรม" },
{ word:"familiar", meaning:"คุ้นเคย" },
{ word:"fancy", meaning:"หรูหรา, ชอบ" },
{ word:"far", meaning:"ไกล" },
{ word:"fascinating", meaning:"น่าหลงใหล, น่าทึ่ง" },
{ word:"fashionable", meaning:"ทันสมัย" },
{ word:"fasten", meaning:"รัด, ผูก" },
{ word:"favour", meaning:"ความโปรดปราน, ช่วยเหลือ" },
{ word:"fear", meaning:"ความกลัว" },
{ word:"feature", meaning:"คุณลักษณะ, มีบทบาท" },
{ word:"fence", meaning:"รั้ว" },
{ word:"fighting", meaning:"การต่อสู้" },
{ word:"file", meaning:"ไฟล์, แฟ้ม" },
{ word:"financial", meaning:"ทางการเงิน" },
{ word:"fire", meaning:"ไฟ, ไล่ออก" },
{ word:"fitness", meaning:"ความแข็งแรง, ฟิตเนส" },
{ word:"fixed", meaning:"คงที่, ที่แก้ไขแล้ว" },
{ word:"flag", meaning:"ธง" },
{ word:"flood", meaning:"น้ำท่วม" },
{ word:"flour", meaning:"แป้งทำอาหาร" },
{ word:"flow", meaning:"ไหล" },
{ word:"fold", meaning:"พับ" },
{ word:"folk", meaning:"พื้นบ้าน, ประชาชน" },
{ word:"following", meaning:"ต่อไปนี้, หลังจาก" },
{ word:"force", meaning:"บังคับ, แรง" },
{ word:"forever", meaning:"ตลอดไป" },
{ word:"frame", meaning:"กรอบ" },
{ word:"freeze", meaning:"แช่แข็ง, หยุด" },
{ word:"frequently", meaning:"บ่อยครั้ง" },
{ word:"friendship", meaning:"มิตรภาพ" },
{ word:"frighten", meaning:"ทำให้ตกใจกลัว" },
{ word:"frightened", meaning:"ตกใจกลัว" },
{ word:"frightening", meaning:"น่ากลัว" },
{ word:"frozen", meaning:"แช่แข็ง" },
{ word:"fry", meaning:"ทอด" },
{ word:"fuel", meaning:"เชื้อเพลิง" },
{ word:"function", meaning:"หน้าที่, ฟังก์ชัน" },
{ word:"fur", meaning:"ขนสัตว์" },
{ word:"further", meaning:"เพิ่มเติม, ไกลออกไป" },
{ word:"garage", meaning:"อู่ซ่อมรถ, โรงรถ" },
{ word:"gather", meaning:"รวบรวม, ชุมนุม" },
{ word:"generally", meaning:"โดยทั่วไป" },
{ word:"generation", meaning:"รุ่น, ยุค" },
{ word:"generous", meaning:"ใจกว้าง, โอบอ้อมอารี" },
{ word:"gentle", meaning:"อ่อนโยน" },
{ word:"gentleman", meaning:"สุภาพบุรุษ" },
{ word:"ghost", meaning:"ผี" },
{ word:"giant", meaning:"ยักษ์, ยิ่งใหญ่" },
{ word:"glad", meaning:"ดีใจ" },
{ word:"global", meaning:"ระดับโลก, ทั่วโลก" },
{ word:"glove", meaning:"ถุงมือ" },
{ word:"go", meaning:"ไป" },
{ word:"goods", meaning:"สินค้า" },
{ word:"grade", meaning:"เกรด, ระดับ" },
{ word:"graduate", meaning:"จบการศึกษา" },
{ word:"grain", meaning:"เมล็ดพืช" },
{ word:"grateful", meaning:"กตัญญู, รู้สึกขอบคุณ" },
{ word:"growth", meaning:"การเติบโต" },
{ word:"guard", meaning:"ยาม, ป้องกัน" },
{ word:"guilty", meaning:"มีความผิด, รู้สึกผิด" },
{ word:"hand", meaning:"มือ, ส่งให้" },
{ word:"hang", meaning:"แขวน" },
{ word:"happiness", meaning:"ความสุข" },
{ word:"hardly", meaning:"แทบจะไม่" },
{ word:"hate", meaning:"เกลียด" },
{ word:"head", meaning:"หัว, หัวหน้า" },
{ word:"headline", meaning:"พาดหัวข่าว" },
{ word:"heating", meaning:"ระบบทำความร้อน" },
{ word:"heavily", meaning:"อย่างหนัก" },
{ word:"helicopter", meaning:"เฮลิคอปเตอร์" },
{ word:"highlight", meaning:"เน้นย้ำ, จุดเด่น" },
{ word:"highly", meaning:"อย่างมาก" },
{ word:"hire", meaning:"จ้าง" },
{ word:"historic", meaning:"ประวัติศาสตร์, สำคัญ" },
{ word:"historical", meaning:"ทางประวัติศาสตร์" },
{ word:"honest", meaning:"ซื่อสัตย์" },
{ word:"horrible", meaning:"สยดสยอง, แย่มาก" },
{ word:"horror", meaning:"ความสยองขวัญ" },
{ word:"host", meaning:"เจ้าภาพ" },
{ word:"hunt", meaning:"ล่า" },
{ word:"hurricane", meaning:"พายุเฮอร์ริเคน" },
{ word:"hurry", meaning:"รีบ" },
{ word:"identity", meaning:"อัตลักษณ์, ตัวตน" },
{ word:"ignore", meaning:"เพิกเฉย" },
{ word:"illegal", meaning:"ผิดกฎหมาย" },
{ word:"imaginary", meaning:"สมมุติ, ในจินตนาการ" },
{ word:"immediate", meaning:"ทันที" },
{ word:"immigrant", meaning:"ผู้อพยพ" },
{ word:"impact", meaning:"ผลกระทบ" },
{ word:"import", meaning:"นำเข้า" },
{ word:"importance", meaning:"ความสำคัญ" },
{ word:"impression", meaning:"ความประทับใจ" },
{ word:"impressive", meaning:"น่าประทับใจ" },
{ word:"improvement", meaning:"การปรับปรุง" },
{ word:"incredibly", meaning:"อย่างเหลือเชื่อ" },
{ word:"indeed", meaning:"จริงๆ แล้ว, แน่นอน" },
{ word:"indicate", meaning:"ระบุ, บ่งชี้" },
{ word:"indirect", meaning:"อ้อม, ไม่ตรง" },
{ word:"indoor", meaning:"ในร่ม" },
{ word:"indoors", meaning:"ในอาคาร, ในร่ม" },
{ word:"influence", meaning:"อิทธิพล" },
{ word:"ingredient", meaning:"ส่วนผสม" },
{ word:"injure", meaning:"ทำให้บาดเจ็บ" },
{ word:"injured", meaning:"บาดเจ็บ" },
{ word:"innocent", meaning:"บริสุทธิ์, ไร้เดียงสา" },
{ word:"intelligence", meaning:"สติปัญญา, ข้อมูลลับ" },
{ word:"intend", meaning:"ตั้งใจ" },
{ word:"intention", meaning:"ความตั้งใจ" },
{ word:"invest", meaning:"ลงทุน" },
{ word:"investigate", meaning:"สืบสวน" },
{ word:"involved", meaning:"เกี่ยวข้อง" },
{ word:"iron", meaning:"เหล็ก, เตารีด" },
{ word:"issue", meaning:"ประเด็น, ปัญหา" },
{ word:"IT", meaning:"เทคโนโลยีสารสนเทศ" },
{ word:"journal", meaning:"วารสาร" },
{ word:"judge", meaning:"ผู้พิพากษา, ตัดสิน" },
{ word:"keen", meaning:"กระตือรือร้น, คม" },
{ word:"key", meaning:"กุญแจ, สำคัญ" },
{ word:"keyboard", meaning:"คีย์บอร์ด" },
{ word:"kick", meaning:"เตะ" },
{ word:"killing", meaning:"การฆ่า" },
{ word:"kind (caring)", meaning:"ใจดี, เมตตา" },
{ word:"kiss", meaning:"จูบ" },
{ word:"knock", meaning:"เคาะ" },
{ word:"label", meaning:"ฉลาก, ป้าย" },
{ word:"laboratory", meaning:"ห้องปฏิบัติการ" },
{ word:"lack", meaning:"ขาดแคลน" },
{ word:"latest", meaning:"ล่าสุด" },
{ word:"lay", meaning:"วาง, วางไข่" },
{ word:"layer", meaning:"ชั้น" },
{ word:"lead1", meaning:"นำ, พาไป" },
{ word:"leading", meaning:"ชั้นนำ" },
{ word:"leaf", meaning:"ใบไม้" },
{ word:"leather", meaning:"หนังแท้" },
{ word:"legal", meaning:"ถูกกฎหมาย, ทางกฎหมาย" },
{ word:"leisure", meaning:"เวลาว่าง" },
{ word:"length", meaning:"ความยาว" },
{ word:"level", meaning:"ระดับ" },
{ word:"lie2 (tell a lie)", meaning:"โกหก" },
{ word:"like (find sb/sth pleasant)", meaning:"ชอบ" },
{ word:"limit", meaning:"จำกัด" },
{ word:"lip", meaning:"ริมฝีปาก" },
{ word:"liquid", meaning:"ของเหลว" },
{ word:"literature", meaning:"วรรณคดี" },
{ word:"live2", meaning:"สด, ถ่ายทอดสด" },
{ word:"living", meaning:"การดำรงชีวิต, มีชีวิต" },
{ word:"local", meaning:"ท้องถิ่น" },
{ word:"locate", meaning:"ตั้งอยู่, หาที่ตั้ง" },
{ word:"located", meaning:"ตั้งอยู่ที่" },
{ word:"location", meaning:"สถานที่ตั้ง" },
{ word:"lonely", meaning:"เหงา" },
{ word:"loss", meaning:"การสูญเสีย" },
{ word:"luxury", meaning:"หรูหรา" },
{ word:"mad", meaning:"บ้า, โกรธ" },
{ word:"magic", meaning:"เวทมนตร์" },
{ word:"mainly", meaning:"ส่วนใหญ่" },
{ word:"mall", meaning:"ห้างสรรพสินค้า" },
{ word:"management", meaning:"การจัดการ" },
{ word:"market", meaning:"ตลาด" },
{ word:"marketing", meaning:"การตลาด" },
{ word:"marriage", meaning:"การแต่งงาน" },
{ word:"meanwhile", meaning:"ในขณะเดียวกัน" },
{ word:"measure", meaning:"วัด, มาตรการ" },
{ word:"medium", meaning:"ปานกลาง, สื่อ" },
{ word:"mental", meaning:"ทางจิต" },
{ word:"mention", meaning:"กล่าวถึง" },
{ word:"mess", meaning:"ความยุ่งเหยิง" },
{ word:"mild", meaning:"อ่อน, ไม่รุนแรง" },
{ word:"mine (hole in the ground)", meaning:"เหมืองแร่" },
{ word:"mix", meaning:"ผสม" },
{ word:"mixture", meaning:"ส่วนผสม" },
{ word:"mood", meaning:"อารมณ์" },
{ word:"move", meaning:"เคลื่อนไหว, ย้าย" },
{ word:"mud", meaning:"โคลน" },
{ word:"murder", meaning:"ฆาตกรรม" },
{ word:"muscle", meaning:"กล้ามเนื้อ" },
{ word:"musical", meaning:"เกี่ยวกับดนตรี" },
{ word:"mystery", meaning:"ความลับ, ปริศนา" },
{ word:"nail", meaning:"เล็บ, ตะปู" },
{ word:"narrative", meaning:"การบรรยาย, เรื่องเล่า" },
{ word:"nation", meaning:"ประเทศ, ชาติ" },
{ word:"native", meaning:"พื้นเมือง, โดยกำเนิด" },
{ word:"naturally", meaning:"โดยธรรมชาติ" },
{ word:"necessarily", meaning:"จำเป็นต้อง" },
{ word:"need", meaning:"ต้องการ, จำเป็น" },
{ word:"needle", meaning:"เข็ม" },
{ word:"neighbourhood", meaning:"ย่าน, ละแวกบ้าน" },
{ word:"neither", meaning:"ไม่ทั้งสอง" },
{ word:"net", meaning:"ตาข่าย, สุทธิ" },
{ word:"next", meaning:"ถัดไป" },
{ word:"nor", meaning:"และไม่" },
{ word:"normal", meaning:"ปกติ" },
{ word:"northern", meaning:"ทางเหนือ" },
{ word:"note", meaning:"บันทึก, โน้ต" },
{ word:"now", meaning:"ตอนนี้" },
{ word:"nuclear", meaning:"นิวเคลียร์" },
{ word:"obvious", meaning:"ชัดเจน" },
{ word:"obviously", meaning:"อย่างเห็นได้ชัด" },
{ word:"occasion", meaning:"โอกาส" },
{ word:"occur", meaning:"เกิดขึ้น" },
{ word:"odd", meaning:"แปลก, เลขคี่" },
{ word:"official", meaning:"ทางการ, เจ้าหน้าที่" },
{ word:"old-fashioned", meaning:"ล้าสมัย" },
{ word:"once", meaning:"ครั้งหนึ่ง" },
{ word:"operation", processing:"การดำเนินการ, ผ่าตัด" },
{ word:"organized", meaning:"มีระเบียบ" },
{ word:"organizer", meaning:"ผู้จัดงาน" },
{ word:"original", meaning:"ดั้งเดิม, ต้นฉบับ" },
{ word:"originally", meaning:"แต่แรกเริ่ม" },
{ word:"ought", meaning:"ควรจะ" },
{ word:"ours", meaning:"ของพวกเรา" },
{ word:"outdoor", meaning:"กลางแจ้ง" },
{ word:"outdoors", meaning:"กลางแจ้ง, ข้างนอก" },
{ word:"pack", meaning:"ห่อ, บรรจุ" },
{ word:"package", meaning:"พัสดุ, แพ็กเกจ" },
{ word:"painful", meaning:"เจ็บปวด" },
{ word:"pale", meaning:"ซีด" },
{ word:"pan", meaning:"กระทะ" },
{ word:"participate", meaning:"มีส่วนร่วม" },
{ word:"particularly", meaning:"โดยเฉพาะอย่างยิ่ง" },
{ word:"pass", meaning:"ผ่าน" },
{ word:"passion", meaning:"ความหลงใหล" },
{ word:"path", meaning:"เส้นทาง" },
{ word:"payment", meaning:"การชำระเงิน" },
{ word:"peaceful", meaning:"สงบสุข" },
{ word:"percentage", meaning:"เปอร์เซ็นต์" },
{ word:"perfectly", meaning:"อย่างสมบูรณ์แบบ" },
{ word:"performance", meaning:"การแสดง, ประสิทธิภาพ" },
{ word:"personally", meaning:"ส่วนตัว, โดยส่วนตัว" },
{ word:"persuade", meaning:"โน้มน้าว" },
{ word:"photographer", meaning:"ช่างภาพ" },
{ word:"photography", meaning:"การถ่ายภาพ" },
{ word:"pin", meaning:"เข็มหมุด" },
{ word:"pipe", meaning:"ท่อ, ไปป์" },
{ word:"place", meaning:"สถานที่" },
{ word:"planning", meaning:"การวางแผน" },
{ word:"pleasant", meaning:"น่าพึงพอใจ, ยินดี" },
{ word:"pleasure", meaning:"ความยินดี" },
{ word:"plenty", meaning:"มากมาย" },
{ word:"plot", meaning:"โครงเรื่อง, พล็อต" },
{ word:"plus1", meaning:"บวก, เพิ่มเติม" },
{ word:"poem", meaning:"บทกวี" },
{ word:"poet", meaning:"กวี" },
{ word:"poetry", meaning:"บทกวี" },
{ word:"point", meaning:"จุด, ชี้" },
{ word:"poison", meaning:"ยาพิษ" },
{ word:"poisonous", meaning:"มีพิษ" },
{ word:"policy", meaning:"นโยบาย" },
{ word:"political", meaning:"ทางการเมือง" },
{ word:"politician", meaning:"นักการเมือง" },
{ word:"politics", meaning:"การเมือง" },
{ word:"port", meaning:"ท่าเรือ" },
{ word:"portrait", meaning:"ภาพภาพเหมือน" },
{ word:"possibly", meaning:"อาจจะ" },
{ word:"pot", meaning:"หม้อ" },
{ word:"pour", meaning:"เท" },
{ word:"poverty", meaning:"ความยากจน" },
{ word:"powder", meaning:"ผง, แป้ง" },
{ word:"powerful", meaning:"ทรงพลัง" },
{ word:"practical", meaning:"ใช้งานได้จริง" },
{ word:"pray", meaning:"อธิษฐาน, สวดมนต์" },
{ word:"prayer", meaning:"การอธิษฐาน" },
{ word:"prediction", meaning:"การทำนาย" },
{ word:"prepared", meaning:"เตรียมพร้อม" },
{ word:"presentation", meaning:"การนำเสนอ" },
{ word:"press", meaning:"กด, สื่อมวลชน" },
{ word:"pressure", meaning:"ความกดดัน, ความดัน" },
{ word:"pretend", meaning:"แกล้งทำ, เสแสร้ง" },
{ word:"previous", meaning:"ก่อนหน้า" },
{ word:"previously", meaning:"ก่อนหน้านี้" },
{ word:"priest", meaning:"นักบวช" },
{ word:"primary", meaning:"ประถมศึกษา, หลัก" },
{ word:"prince", meaning:"เจ้าชาย" },
{ word:"princess", meaning:"เจ้าหญิง" },
{ word:"printing", meaning:"การพิมพ์" },
{ word:"prisoner", meaning:"นักโทษ" },
{ word:"private", meaning:"ส่วนตัว" },
{ word:"producer", meaning:"ผู้ผลิต" },
{ word:"production", meaning:"การผลิต" },
{ word:"profession", meaning:"อาชีพ" },
{ word:"profit", meaning:"กำไร" },
{ word:"program", meaning:"โปรแกรม" },
{ word:"promote", meaning:"ส่งเสริม, เลื่อนขั้น" },
{ word:"proper", meaning:"เหมาะสม" },
{ word:"properly", meaning:"อย่างถูกต้อง" },
{ word:"property", meaning:"ทรัพย์สิน" },
{ word:"protest", meaning:"ประท้วง" },
{ word:"proud", meaning:"ภูมิใจ" },
{ word:"prove", meaning:"พิสูจน์" },
{ word:"pull", meaning:"ดึง" },
{ word:"punish", meaning:"ลงโทษ" },
{ word:"punishment", meaning:"การลงโทษ" },
{ word:"push", meaning:"ผลัก" },
{ word:"qualification", meaning:"คุณสมบัติ" },
{ word:"qualified", meaning:"มีคุณสมบัติ" },
{ word:"qualify", meaning:"มีคุณสมบัติเหมาะสม" },
{ word:"queue", meaning:"คิว, ต่อคิว" },
{ word:"quit", meaning:"เลิก, ลาออก" },
{ word:"quotation", meaning:"คำอ้างอิง, ใบเสนอราคา" },
{ word:"quote", meaning:"อ้างอิง" },
{ word:"race (people)", meaning:"เชื้อชาติ" },
{ word:"racing", meaning:"การแข่งรถ, การแข่งขัน" },
{ word:"range", meaning:"ขอบเขต, ช่วง" },
{ word:"rare", meaning:"หายาก" },
{ word:"rarely", meaning:"แทบจะไม่, นานๆ ครั้ง" },
{ word:"reaction", meaning:"ปฏิกิริยา" },
{ word:"reality", meaning:"ความเป็นจริง" },
{ word:"receipt", meaning:"ใบเสร็จ" },
{ word:"recommendation", meaning:"คำแนะนำ" },
{ word:"reference", meaning:"การอ้างอิง" },
{ word:"reflect", meaning:"สะท้อน" },
{ word:"regularly", meaning:"เป็นประจำ" },
{ word:"reject", meaning:"ปฏิเสธ" },
{ word:"relate", meaning:"เกี่ยวข้อง" },
{ word:"related", meaning:"ที่เกี่ยวข้อง" },
{ word:"relation", meaning:"ความสัมพันธ์" },
{ word:"relative", meaning:"ญาติ" },
{ word:"relaxed", meaning:"ผ่อนคลาย" },
{ word:"relaxing", meaning:"น่าผ่อนคลาย" },
{ word:"release", meaning:"ปล่อย, ปล่อยตัว" },
{ word:"reliable", meaning:"น่าเชื่อถือ" },
{ word:"religion", meaning:"ศาสนา" },
{ word:"religious", meaning:"ทางศาสนา" },
{ word:"remain", meaning:"ยังคงอยู่" },
{ word:"remind", meaning:"เตือนความจำ" },
{ word:"remote", meaning:"ห่างไกล, รีโมท" },
{ word:"rent", meaning:"เช่า" },
{ word:"repair", meaning:"ซ่อมแซม" },
{ word:"repeat", meaning:"ทำซ้ำ" },
{ word:"repeated", meaning:"ทำซ้ำซาก" },
{ word:"represent", meaning:"เป็นตัวแทน" },
{ word:"request", meaning:"ร้องขอ" },
{ word:"require", meaning:"ต้องการ, บังคับ" },
{ word:"reservation", meaning:"การจอง" },
{ word:"resource", meaning:"ทรัพยากร" },
{ word:"respect", meaning:"เคารพ" },
{ word:"responsibility", meaning:"ความรับผิดชอบ" },
{ word:"responsible", meaning:"มีความรับผิดชอบ" },
{ word:"result", meaning:"ผลลัพธ์" },
{ word:"retire", meaning:"เกษียณอายุ" },
{ word:"retired", meaning:"เกษียณแล้ว" },
{ word:"revise", meaning:"ทบทวน, แก้ไข" },
{ word:"ring2", meaning:"สั่น, โทร" },
{ word:"rise", meaning:"ขึ้น, เพิ่มขึ้น" },
{ word:"risk", meaning:"ความเสี่ยง" },
{ word:"robot", meaning:"หุ่นยนต์" },
{ word:"roll", meaning:"ม้วน, กลิ้ง" },
{ word:"romantic", meaning:"โรแมนติก" },
{ word:"rope", meaning:"เชือก" },
{ word:"rough", meaning:"หยาบ, ขรุขระ" },
{ word:"row1", meaning:"แถว" },
{ word:"royal", meaning:"เกี่ยวกับราชวงศ์" },
{ word:"rugby", meaning:"รักบี้" },
{ word:"rule", meaning:"กฎ, กฎเกณฑ์" },
{ word:"safety", meaning:"ความปลอดภัย" },
{ word:"sail", meaning:"แล่นเรือ" },
{ word:"sailor", meaning:"ลูกเรือ, กะลาสี" },
{ word:"sample", meaning:"ตัวอย่าง" },
{ word:"sand", meaning:"ทราย" },
{ word:"scan", meaning:"สแกน" },
{ word:"scientific", meaning:"ทางวิทยาศาสตร์" },
{ word:"script", meaning:"บทภาพยนตร์, บทละคร" },
{ word:"sculpture", meaning:"ประติมากรรม" },
{ word:"secondary", meaning:"ระดับมัธยม, รองลงมา" },
{ word:"security", meaning:"ความปลอดภัย" },
{ word:"seed", meaning:"เมล็ดพันธุ์" },
{ word:"sensible", meaning:"สมเหตุสมผล" },
{ word:"separate", meaning:"แยก" },
{ word:"seriously", meaning:"อย่างจริงจัง" },
{ word:"servant", meaning:"คนรับใช้" },
{ word:"set (put)", meaning:"วาง, ตั้งค่า" },
{ word:"set (group)", meaning:"ชุด, กลุ่ม" },
{ word:"setting", meaning:"ฉาก, การตั้งค่า" },
{ word:"sex", meaning:"เพศ, เซ็กส์" },
{ word:"sexual", meaning:"ทางเพศ" },
{ word:"shake", meaning:"เขย่า, สั่น" },
{ word:"share", meaning:"แบ่งปัน, หุ้น" },
{ word:"sharp", meaning:"คม" },
{ word:"shelf", meaning:"ชั้นวางของ" },
{ word:"shell", meaning:"เปลือกหอย, เปลือก" },
{ word:"shift", meaning:"กะการทำงาน, ย้าย" },
{ word:"shine", meaning:"ส่องแสง" },
{ word:"shiny", meaning:"เงางาม" },
{ word:"shoot", meaning:"ยิง, ถ่ายภาพ" },
{ word:"shy", meaning:"ขี้อาย" },
{ word:"sight", meaning:"การมองเห็น, สายตา" },
{ word:"signal", meaning:"สัญญาณ" },
{ word:"silent", meaning:"เงียบ" },
{ word:"silly", meaning:"งี่เง่า, ไร้สาระ" },
{ word:"similarity", meaning:"ความคล้ายคลึงกัน" },
{ word:"similarly", meaning:"ในทำนองเดียวกัน" },
{ word:"simply", meaning:"ง่ายๆ, เพียงแค่" },
{ word:"since", meaning:"ตั้งแต่, เนื่องจาก" },
{ word:"sink", meaning:"อ่างล้างจาน, จม" },
{ word:"slice", meaning:"ชิ้นบาง, หั่น" },
{ word:"slightly", meaning:"เล็กน้อย" },
{ word:"slow", meaning:"ช้า" },
{ word:"smart", meaning:"ฉลาด, ดูดี" },
{ word:"smooth", meaning:"ราบรื่น, เรียบ" },
{ word:"software", meaning:"ซอฟต์แวร์" },
{ word:"soil", meaning:"ดิน" },
{ word:"solid", meaning:"ของแข็ง" },
{ word:"sort", meaning:"ประเภท, คัดแยก" },
{ word:"southern", meaning:"ทางใต้" },
{ word:"specifically", meaning:"โดยเฉพาะเจาะจง" },
{ word:"spending", meaning:"การใช้จ่าย" },
{ word:"spicy", meaning:"เผ็ด" },
{ word:"spirit", meaning:"วิญญาณ, จิตวิญญาณ" },
{ word:"spoken", meaning:"ภาษาพูด" },
{ word:"spot", meaning:"จุด, สถานที่" },
{ word:"spread", meaning:"แพร่กระจาย" },
{ word:"spring", meaning:"ฤดูใบไม้ผลิ, สปริง" },
{ word:"stadium", meaning:"สนามกีฬา" },
{ word:"staff", meaning:"พนักงาน, บุคลากร" },
{ word:"standard", meaning:"มาตรฐาน" },
{ word:"state", meaning:"รัฐ, สภาพ" },
{ word:"statistic", meaning:"สถิติ" },
{ word:"statue", meaning:"รูปปั้น" },
{ word:"stick (push into/attach)", meaning:"ติด, เสียบ" },
{ word:"stick (piece of wood)", meaning:"กิ่งไม้, ไม้เท้า" },
{ word:"still", meaning:"ยังคง" },
{ word:"store", meaning:"ร้านค้า, จัดเก็บ" },
{ word:"stranger", meaning:"คนแปลกหน้า" },
{ word:"strength", meaning:"ความแข็งแร็ง" },
{ word:"string", meaning:"เชือก, สายตรา" },
{ word:"strongly", meaning:"อย่างแข็งแกร่ง" },
{ word:"studio", meaning:"สตูดิโอ" },
{ word:"stuff", meaning:"สิ่งของ" },
{ word:"substance", meaning:"สาร, เนื้อหาสาระ" },
{ word:"successfully", meaning:"ประสบความสำเร็จ" },
{ word:"sudden", meaning:"กะทันหัน" },
{ word:"suffer", meaning:"ทรมาน, ทุกข์ทรมาน" },
{ word:"suit", meaning:"สูท, เหมาะสม" },
{ word:"suitable", meaning:"เหมาะสม" },
{ word:"summarize", meaning:"สรุป" },
{ word:"summary", meaning:"บทสรุป" },
{ word:"supply", meaning:"จัดหา, เสบียง" },
{ word:"supporter", meaning:"ผู้สนับสนุน" },
{ word:"surely", meaning:"อย่างแน่นอน" },
{ word:"surface", meaning:"พื้นผิว" },
{ word:"survive", meaning:"อยู่รอด" },
{ word:"swim", meaning:"ว่ายน้ำ" },
{ word:"switch", meaning:"สวิตช์, สลับ" },
{ word:"symptom", meaning:"อาการ" },
{ word:"tail", meaning:"หาง" },
{ word:"talent", meaning:"พรสวรรค์" },
{ word:"talented", meaning:"มีพรสวรรค์" },
{ word:"tape", meaning:"เทป" },
{ word:"tax", meaning:"ภาษี" },
{ word:"technical", meaning:"ทางเทคนิค" },
{ word:"technique", meaning:"เทคนิค" },
{ word:"tend", meaning:"มักจะ" },
{ word:"tent", meaning:"เต็นท์" },
{ word:"that", meaning:"นั่น, ที่" },
{ word:"theirs", meaning:"ของพวกเขา" },
{ word:"theme", meaning:"ธีม, หัวข้อ" },
{ word:"theory", meaning:"ทฤษฎี" },
{ word:"therefore", meaning:"ดังนั้น" },
{ word:"this", meaning:"นี้" },
{ word:"though", meaning:"แม้ว่า" },
{ word:"throat", meaning:"ลำคอ" },
{ word:"throughout", meaning:"ตลอด, ทั่วทั้ง" },
{ word:"tight", meaning:"แน่น" },
{ word:"till", meaning:"จนกระทั่ง" },
{ word:"tin", meaning:"กระป๋อง, ดีบุก" },
{ word:"tiny", meaning:"เล็กจิ๋ว" },
{ word:"tip", meaning:"เคล็ดลับ, เงินรางวัล" },
{ word:"toe", meaning:"นิ้วเท้า" },
{ word:"tongue", meaning:"ลิ้น" },
{ word:"total", meaning:"ทั้งหมด" },
{ word:"totally", meaning:"โดยสิ้นเชิง" },
{ word:"touch", meaning:"สัมผัส" },
{ word:"tour", meaning:"เที่ยว, ทัวร์" },
{ word:"trade", meaning:"การค้า" },
{ word:"translate", meaning:"แปล" },
{ word:"translation", meaning:"การแปล" },
{ word:"transport", meaning:"การขนส่ง" },
{ word:"treat", meaning:"รักษา, ปฏิบัติต่อ" },
{ word:"treatment", meaning:"การรักษา" },
{ word:"trend", meaning:"แนวโน้ม" },
{ word:"trick", meaning:"เคล็ดลับ, หลอกลวง" },
{ word:"truth", meaning:"ความจริง" },
{ word:"tube", meaning:"หลอด, ท่อ" },
{ word:"type", meaning:"ประเภท, พิมพ์" },
{ word:"typically", meaning:"ตามปกติ, โดยทั่วไป" },
{ word:"tyre", meaning:"ยางรถยนต์" },
{ word:"ugly", meaning:"น่าเกลียด" },
{ word:"unable", meaning:"ไม่สามารถ" },
{ word:"uncomfortable", meaning:"ไม่สบาย, อึดอัด" },
{ word:"underwear", meaning:"ชุดชั้นใน" },
{ word:"unemployed", meaning:"ว่างงาน" },
{ word:"unemployment", meaning:"การว่างงาน" },
{ word:"unfair", meaning:"ไม่ยุติธรรม" },
{ word:"union", meaning:"สหภาพ" },
{ word:"unless", meaning:"เว้นแต่ว่า" },
{ word:"unlike", meaning:"แตกต่างจาก" },
{ word:"unlikely", meaning:"ไม่น่าเป็นไปได้" },
{ word:"unnecessary", meaning:"ไม่จำเป็น" },
{ word:"unpleasant", meaning:"ไม่พึงประสงค์" },
{ word:"update", meaning:"ปรับปรุงข้อมูล" },
{ word:"upon", meaning:"บน, เมื่อ" },
{ word:"upset", meaning:"เสียใจ, อารมณ์เสีย" },
{ word:"used1", meaning:"ใช้แล้ว, มือสอง" },
{ word:"used2", meaning:"เคย, เคยชิน" },
{ word:"valuable", meaning:"มีค่า" },
{ word:"value", meaning:"มูลค่า, คุณค่า" },
{ word:"various", meaning:"หลากหลาย" },
{ word:"version", meaning:"เวอร์ชัน, รุ่น" },
{ word:"victim", meaning:"เหยื่อ" },
{ word:"view", meaning:"วิว, มุมมอง" },
{ word:"viewer", meaning:"ผู้ชม" },
{ word:"violent", meaning:"รุนแรง" },
{ word:"volunteer", meaning:"อาสาสมัคร" },
{ word:"vote", meaning:"ลงคะแนน, โหวต" },
{ word:"warm", meaning:"อบอุ่น" },
{ word:"warn", meaning:"เตือน" },
{ word:"warning", meaning:"คำเตือน" },
{ word:"waste", meaning:"เสียเปล่า, ขยะ" },
{ word:"water", meaning:"น้ำ" },
{ word:"wave", meaning:"คลื่น, โบกมือ" },
{ word:"weapon", meaning:"อาวุธ" },
{ word:"weigh", meaning:"ชั่งน้ำหนัก" },
{ word:"western", meaning:"ทางทิศตะวันตก" },
{ word:"whatever", meaning:"อะไรก็ตาม" },
{ word:"whenever", meaning:"เมื่อไหร่ก็ตาม" },
{ word:"whether", meaning:"หรือไม่" },
{ word:"while", meaning:"ในขณะที่" },
{ word:"whole", meaning:"ทั้งหมด" },
{ word:"will", meaning:"จะ, พินัยกรรม" },
{ word:"win", meaning:"ชนะ" },
{ word:"wing", meaning:"ปีก" },
{ word:"within", meaning:"ภายใน" },
{ word:"wonder", meaning:"สงสัย, แปลกใจ" },
{ word:"wool", meaning:"ขนแกะ, ขนสัตว์" },
{ word:"worldwide", meaning:"ทั่วโลก" },
{ word:"worry", meaning:"กังวล" },
{ word:"worse", meaning:"แย่กว่า" },
{ word:"worst", meaning:"แย่ที่สุด" },
{ word:"worth", meaning:"มีค่า, คุ้มค่า" },
{ word:"written", meaning:"เป็นลายลักษณ์อักษร" },
{ word:"wrong", meaning:"ผิด" },
{ word:"yard", meaning:"สนาม, หลา" },
{ word:"young", meaning:"เด็ก, หนุ่มสาว" },
{ word:"youth", meaning:"เยาวชน, วัยหนุ่มสาว" }
];