// ==========================================================
// คลังคำศัพท์ TOPIK 1
// ==========================================================
window.flashVocabData1 = [
  { word:"가게", meaning:"ร้าน, ร้านค้า" },
  { word:"가격", meaning:"ราคา" },
  { word:"가구", meaning:"เฟอร์นิเจอร์" },
  { word:"가방", meaning:"กระเป๋า" },
  { word:"가수", meaning:"นักร้อง" },
  { word:"가운데", meaning:"กลาง" },
  { word:"가위", meaning:"กรรไกร" },
  { word:"가을", meaning:"ฤดูใบไม้ร่วง" },
  { word:"가족", meaning:"ครอบครัว" },
  { word:"간식", meaning:"อาหารว่าง" },
  { word:"간호사", meaning:"พยาบาล" },
  { word:"감기", meaning:"หวัด" },
  { word:"감사", meaning:"การขอบคุณ" },
  { word:"감자", meaning:"มันฝรั่ง" },
  { word:"값", meaning:"ราคา, ค่า" },
  { word:"강", meaning:"แม่น้ำ" },
  { word:"강아지", meaning:"ลูกสุนัข" },
  { word:"개", meaning:"สุนัข, หมา" },
  { word:"거리", meaning:"ถนน, ทาง" },
  { word:"거실", meaning:"ห้องรับแขก" },
  { word:"거울", meaning:"กระจก" },
  { word:"거절", meaning:"การปฏิเสธ" },
  { word:"거짓말", meaning:"การพูดโกหก, คำพูดโกหก" },
  { word:"걱정", meaning:"ความกังวล, ความเป็นห่วง" },
  { word:"건강", meaning:"สุขภาพ" },
  { word:"건너편", meaning:"ฝั่งตรงข้าม" },
  { word:"건물", meaning:"ตึก" },
  { word:"검사", meaning:"การตรวจ" },
  { word:"검은색", meaning:"สีดำ" },
  { word:"것", meaning:"สิ่ง, ของ" },
  { word:"게임", meaning:"เกม" },
  { word:"겨울", meaning:"ฤดูหนาว" },
  { word:"결과", meaning:"ผล, ผลลัพธ์" },
  { word:"결석", meaning:"การขาด, การขาดเรียน, การไม่เข้าร่วม" },
  { word:"결심", meaning:"การตัดสินใจ, การตกลงใจ" },
  { word:"결정", meaning:"การตัดสินใจ, การตัดสิน" },
  { word:"결혼", meaning:"การแต่งงาน" },
  { word:"결혼식", meaning:"งานแต่งงาน" },
  { word:"경기", meaning:"การแข่งขัน" },
  { word:"경찰", meaning:"ตำรวจ" },
  { word:"경치", meaning:"ทิวทัศน์, วิว" },
  { word:"경험", meaning:"ประสบการณ์" },
  { word:"계단", meaning:"บันได" },
  { word:"계란", meaning:"ไข่, ไข่ไก่" },
  { word:"계산", meaning:"การคิดเงิน, การคำนวณ, การคิดเลข" },
  { word:"계절", meaning:"ฤดู, ฤดูกาล" },
  { word:"계획", meaning:"แผน, แผนการ, โครงการ" },
  { word:"고기", meaning:"เนื้อ, เนื้อสัตว์" },
  { word:"고등학교", meaning:"โรงเรียนมัธยมปลาย" },
  { word:"고등학생", meaning:"นักเรียนมัธยมปลาย" },
  { word:"고민", meaning:"ความกลุ้มใจ, ความกังวล" },
  { word:"고속버스", meaning:"รถโดยสารประจำทางด่วนพิเศษ" },
  { word:"고양이", meaning:"แมว" },
  { word:"고장", meaning:"การเสีย, การพัง, การไม่ทำงาน" },
  { word:"고향", meaning:"บ้านเกิด" },
  { word:"곳", meaning:"สถานที่, ที่, จุด" },
  { word:"공", meaning:"ลูกบอล" },
  { word:"공무원", meaning:"ข้าราชการ" },
  { word:"공부", meaning:"การเรียน, การเรียนหนังสือ" },
  { word:"공원", meaning:"สวนสาธารณะ, สวน" },
  { word:"공장", meaning:"โรงงาน" },
  { word:"공짜", meaning:"ฟรี" },
  { word:"공책", meaning:"สมุด, สมุดจดบันทึก" },
  { word:"공항", meaning:"สนามบิน" },
  { word:"공휴일", meaning:"วันหยุดราชการ" },
  { word:"과거", meaning:"อดีต" },
  { word:"과일", meaning:"ผลไม้" },
  { word:"과자", meaning:"ขนม" },
  { word:"관계", meaning:"ความสัมพันธ์, ความเกี่ยวข้อง" },
  { word:"관광", meaning:"การท่องเที่ยว" },
  { word:"관광객", meaning:"นักท่องเที่ยว" },
  { word:"관광지", meaning:"สถานที่ท่องเที่ยว" },
  { word:"관심", meaning:"ความสนใจ" },
  { word:"광고", meaning:"การโฆษณา" },
  { word:"교과서", meaning:"ตำราเรียน, หนังสือเรียน" },
  { word:"교사", meaning:"ครู, อาจารย์" },
  { word:"교수", meaning:"อาจารย์, ศาสตราจารย์" },
  { word:"교실", meaning:"ห้องเรียน" },
  { word:"교육", meaning:"การศึกษา, การอบรม, การฝึกฝน" },
  { word:"교통", meaning:"การจราจร, การคมนาคม" },
  { word:"교통비", meaning:"ค่าโดยสาร" },
  { word:"교통사고", meaning:"อุบัติเหตุจราจร" },
  { word:"교환", meaning:"การเปลี่ยน, การแลกเปลี่ยน" },
  { word:"교회", meaning:"โบสถ์" },
  { word:"구경", meaning:"การดู, การเยี่ยมชม, การชม" },
  { word:"구두", meaning:"รองเท้า" },
  { word:"구름", meaning:"เมฆ, ก้อนเมฆ" },
  { word:"국내", meaning:"ในประเทศ" },
  { word:"국적", meaning:"สัญชาติ" },
  { word:"국제", meaning:"ระหว่างประเทศ, นานาชาติ" },
  { word:"군인", meaning:"ทหาร" },
  { word:"귀", meaning:"หู" },
  { word:"귀걸이", meaning:"ต่างหู, ตุ้มหู" },
  { word:"규칙", meaning:"กฎ, กฎเกณฑ์" },
  { word:"그동안", meaning:"ในช่วงเวลาที่นั้น, ในช่วงที่ผ่านมา" },
  { word:"그릇", meaning:"ถ้วย" },
  { word:"그림", meaning:"ภาพวาด, ภาพ" },
  { word:"극장", meaning:"โรงภาพยนตร์, โรงหนัง" },
  { word:"근처", meaning:"บริเวณใกล้เคียง, ที่ใกล้ ๆ, แถว" },
  { word:"금지", meaning:"การห้าม, การสั่งห้าม" },
  { word:"기간", meaning:"ระยะเวลา, ช่วงเวลา" },
  { word:"기분", meaning:"อารมณ์" },
  { word:"기숙사", meaning:"หอพัก" },
  { word:"기억", meaning:"ความจำ, การจดจำ" },
  { word:"기온", meaning:"อุณหภูมิ" },
  { word:"기자", meaning:"นักข่าว, ผู้สื่อข่าว, นักหนังสือพิมพ์" },
  { word:"기차", meaning:"รถไฟ" },
  { word:"기차역", meaning:"สถานีรถไฟ" },
  { word:"기차표", meaning:"ตั๋วรถไฟ" },
  { word:"기침", meaning:"การไอ" },
  { word:"기타", meaning:"กีตาร์" },
  { word:"기회", meaning:"โอกาส, หนทาง" },
  { word:"긴장", meaning:"ความตื่นเต้น, ความประหม่า, ความตึงเครียด" },
  { word:"길", meaning:"ถนน, ทาง, ถนนหนทาง" },
  { word:"김밥", meaning:"ข้าวห่อสาหร่าย" },
  { word:"김치", meaning:"กิมจิ" },
  { word:"꽃", meaning:"ดอกไม้" },
  { word:"꽃집", meaning:"ร้านดอกไม้" },
  { word:"꿈", meaning:"ความฝัน" },
  { word:"끝", meaning:"จบ, ท้ายสุด, สุดท้าย" }
];