// ==========================================================
// คลังคำศัพท์ English A2
// ==========================================================
window.flashVocabDataEnA2 = [
  { word: "ability", meaning: "ความสามารถ" },
  { word: "able", meaning: "สามารถ" },
  { word: "abroad", meaning: "ต่างประเทศ" },
  { word: "accept", meaning: "ยอมรับ" },
  { word: "accident", meaning: "อุบัติเหตุ" },
  { word: "according to", meaning: "ตาม, ตามที่" },
  { word: "achieve", meaning: "บรรลุ, ทำให้สำเร็จ" },
  { word: "act", meaning: "กระทำ, แสดง" },
  { word: "active", meaning: "กระฉับกระเฉง" },
  { word: "actually", meaning: "จริงๆแล้ว" },
  { word: "adult", meaning: "ผู้ใหญ่" },
  { word: "advantage", meaning: "ข้อได้เปรียบ, ประโยชน์" },
  { word: "adventure", meaning: "การผจญภัย" },
  { word: "advertise", meaning: "โฆษณา" },
  { word: "advertisement", meaning: "โฆษณา" },
  { word: "advertising", meaning: "การโฆษณา" },
  { word: "affect", meaning: "มีผลต่อ, กระทบ" },
  { word: "after", meaning: "หลัง, หลังจาก" },
  { word: "against", meaning: "ต่อต้าน, ชิดกับ" },
  { word: "ah", meaning: "อ่า, อ๋อ" },
  { word: "airline", meaning: "สายการบิน" },
  { word: "alive", meaning: "มีชีวิต" },
  { word: "all", meaning: "ทั้งหมด" },
  { word: "all right", meaning: "โอเค, ถูกต้อง" },
  { word: "allow", meaning: "อนุญาต" },
  { word: "almost", meaning: "เกือบ" },
  { word: "alone", meaning: "คนเดียว, เพียงลำพัง" },
  { word: "along", meaning: "ตาม" },
  { word: "already", meaning: "แล้ว" },
  { word: "alternative", meaning: "ทางเลือก" },
  { word: "although", meaning: "ถึงแม้ว่า, แม้ว่า" },
  { word: "among", meaning: "ท่ามกลาง, ในหมู่" },
  { word: "amount", meaning: "จำนวน, ปริมาณ" },
  { word: "ancient", meaning: "โบราณ" },
  { word: "ankle", meaning: "ข้อเท้า" },
  { word: "any", meaning: "ใดๆ" },
  { word: "anybody", meaning: "ใครก็ได้" },
  { word: "any more", meaning: "อีกต่อไป" },
  { word: "anyway", meaning: "อย่างไรก็ตาม" },
  { word: "anywhere", meaning: "ที่ไหนก็ได้" },
  { word: "app", meaning: "แอป, แอปพลิเคชัน" },
  { word: "appear", meaning: "ปรากฏ, ดูเหมือน" },
  { word: "appearance", meaning: "การปรากฏ, รูปลักษณ์" },
  { word: "apply", meaning: "ใช้, สมัคร" },
  { word: "architect", meaning: "สถาปนิก" },
  { word: "architecture", meaning: "สถาปัตยกรรม" },
  { word: "argue", meaning: "โต้แย้ง" },
  { word: "argument", meaning: "ข้อโต้แย้ง, การโต้เถียง" },
  { word: "army", meaning: "กองทัพ" },
  { word: "arrange", meaning: "จัด, จัดเตรียม" },
  { word: "arrangement", meaning: "การจัดเตรียม, ข้อตกลง" },
  { word: "as", meaning: "ขณะที่, เช่น, ตามที่" },
  { word: "asleep", meaning: "นอนหลับ" },
  { word: "assistant", meaning: "ผู้ช่วย" },
  { word: "athlete", meaning: "นักกีฬา" },
  { word: "attack", meaning: "โจมตี, การโจมตี" },
  { word: "attend", meaning: "เข้าร่วม, ดูแล" },
  { word: "attention", meaning: "ความสนใจ" },
  { word: "attractive", meaning: "น่าดึงดูด, มีเสน่ห์" },
  { word: "audience", meaning: "ผู้ชม, ผู้ฟัง" },
  { word: "author", meaning: "ผู้เขียน, ผู้แต่ง" },
  { word: "available", meaning: "มีอยู่, ใช้ได้" },
  { word: "average", meaning: "โดยเฉลี่ย, ธรรมดา" },
  { word: "avoid", meaning: "หลีกเลี่ยง" },
  { word: "award", meaning: "รางวัล, มอบรางวัล" },
  { word: "awful", meaning: "แย่มาก, น่ากลัว" },
  { word: "back", meaning: "หลัง, กลับ" },
  { word: "background", meaning: "พื้นหลัง, ภูมิหลัง" },
  { word: "badly", meaning: "อย่างมาก, แย่" },
  { word: "bar", meaning: "บาร์, ร้านเหล้า, แท่ง" },
  { word: "baseball", meaning: "เบสบอล" },
  { word: "based", meaning: "มีพื้นฐาน, ตั้งอยู่ที่" },
  { word: "basketball", meaning: "บาสเกตบอล" },
  { word: "bean", meaning: "ถั่ว" },
  { word: "bear (animal)", meaning: "หมี" },
  { word: "beat", meaning: "ตี, ชนะ, จังหวะ" },
  { word: "beef", meaning: "เนื้อวัว" },
  { word: "before", meaning: "ก่อน, ก่อนหน้า" },
  { word: "behave", meaning: "ประพฤติ" },
  { word: "behaviour", meaning: "พฤติกรรม" },
  { word: "belong", meaning: "เป็นของ, อยู่ใน" },
  { word: "belt", meaning: "เข็มขัด" },
  { word: "benefit", meaning: "ผลประโยชน์, ประโยชน์" },
  { word: "best", meaning: "ดีที่สุด" },
  { word: "better", meaning: "ดีกว่า" },
  { word: "between", meaning: "ระหว่าง" },
  { word: "billion", meaning: "พันล้าน" },
  { word: "bin", meaning: "ถังขยะ" },
  { word: "biology", meaning: "ชีววิทยา" },
  { word: "birth", meaning: "การเกิด, กำเนิด" },
  { word: "biscuit", meaning: "บิสกิต, คุกกี้" },
  { word: "bit", meaning: "เล็กน้อย, ชิ้นเล็ก" },
  { word: "blank", meaning: "ว่าง, ช่องว่าง" },
  { word: "blood", meaning: "เลือด" },
  { word: "blow", meaning: "ตี, การชก, เป่า" },
  { word: "board", meaning: "กระดาน, คณะ" },
  { word: "boil", meaning: "ต้ม, เดือด" },
  { word: "bone", meaning: "กระดูก" },
  { word: "book", meaning: "หนังสือ, จอง" },
  { word: "borrow", meaning: "ยืม" },
  { word: "boss", meaning: "เจ้านาย" },
  { word: "bottom", meaning: "ด้านล่าง, ก้น" },
  { word: "bowl", meaning: "ชาม" },
  { word: "brain", meaning: "สมอง" },
  { word: "bridge", meaning: "สะพาน" },
  { word: "bright", meaning: "สดใส, ฉลาด" },
  { word: "brilliant", meaning: "ยอดเยี่ยม, ฉลาด" },
  { word: "broken", meaning: "แตก, ชำรุด" },
  { word: "brush", meaning: "แปรง, ปัด" },
  { word: "burn", meaning: "ไหม้, เผา" },
  { word: "businessman", meaning: "นักธุรกิจ" },
  { word: "button", meaning: "ปุ่ม, กระดุม" },
  { word: "camp", meaning: "ค่าย, ตั้งค่าย" },
  { word: "camping", meaning: "การตั้งแคมป์" },
  { word: "can2", meaning: "กระป๋อง" },
  { word: "care", meaning: "ดูแล, ห่วงใย" },
  { word: "careful", meaning: "ระมัดระวัง" },
  { word: "carefully", meaning: "อย่างระมัดระวัง" },
  { word: "carpet", meaning: "พรม" },
  { word: "cartoon", meaning: "การ์ตูน" },
  { word: "case", meaning: "กรณี, เคส" },
  { word: "cash", meaning: "เงินสด" },
  { word: "castle", meaning: "ปราสาท" },
  { word: "catch", meaning: "จับ, คว้า" },
  { word: "cause", meaning: "สาเหตุ, ทำให้เกิด" },
  { word: "celebrate", meaning: "เฉลิมฉลอง" },
  { word: "celebrity", meaning: "คนดัง" },
  { word: "certain", meaning: "แน่นอน, บาง" },
  { word: "certainly", meaning: "แน่นอน" },
  { word: "chance", meaning: "โอกาส, ความบังเอิญ" },
  { word: "character", meaning: "ตัวละคร, บุคลิก" },
  { word: "charity", meaning: "การกุศล" },
  { word: "chat", meaning: "คุย, สนทนา" },
  { word: "check", meaning: "ตรวจสอบ, เช็ค" },
  { word: "chef", meaning: "พ่อครัว" },
  { word: "chemistry", meaning: "เคมี, ความสัมพันธ์" },
  { word: "chip", meaning: "ชิป, เศษ" },
  { word: "choice", meaning: "ทางเลือก" },
  { word: "church", meaning: "โบสถ์" },
  { word: "cigarette", meaning: "บุหรี่" },
  { word: "circle", meaning: "วงกลม, กลุ่ม" },
  { word: "classical", meaning: "คลาสสิก" },
  { word: "clear", meaning: "ชัดเจน, ใส" },
  { word: "clearly", meaning: "อย่างชัดเจน" },
  { word: "clever", meaning: "ฉลาด" },
  { word: "climate", meaning: "ภูมิอากาศ" },
  { word: "close2", meaning: "ปิด" },
  { word: "closed", meaning: "ปิด" },
  { word: "clothing", meaning: "เสื้อผ้า" },
  { word: "cloud", meaning: "เมฆ" },
  { word: "coach", meaning: "โค้ช, รถบัส" },
  { word: "coast", meaning: "ชายฝั่ง" },
  { word: "code", meaning: "รหัส, โค้ดโปรแกรม" },
  { word: "colleague", meaning: "เพื่อนร่วมงาน" },
  { word: "collect", meaning: "เก็บ, รวบรวม" },
  { word: "column", meaning: "คอลัมน์, เสา" },
  { word: "comedy", meaning: "ตลก" },
  { word: "comfortable", meaning: "สบาย" },
  { word: "comment", meaning: "ความคิดเห็น, วิจารณ์" },
  { word: "communicate", meaning: "สื่อสาร" },
  { word: "community", meaning: "ชุมชน" },
  { word: "compete", meaning: "แข่งขัน" },
  { word: "competition", meaning: "การแข่งขัน" },
  { word: "complain", meaning: "บ่น, ร้องเรียน" },
  { word: "completely", meaning: "อย่างสิ้นเชิง" },
  { word: "condition", meaning: "เงื่อนไข, สภาพ" },
  { word: "conference", meaning: "การประชุม" },
  { word: "connect", meaning: "เชื่อมต่อ" },
  { word: "connected", meaning: "เชื่อมต่อ, มีความสัมพันธ์" },
  { word: "consider", meaning: "พิจารณา" },
  { word: "contain", meaning: "บรรจุ, มี" },
  { word: "context", meaning: "บริบท" },
  { word: "continent", meaning: "ทวีป" },
  { word: "continue", meaning: "ต่อเนื่อง, ดำเนินต่อ" },
  { word: "control", meaning: "ควบคุม" },
  { word: "cook", meaning: "ทำอาหาร" },
  { word: "cooker", meaning: "เตา, เครื่องหุงต้ม" },
  { word: "copy", meaning: "สำเนา, คัดลอก" },
  { word: "corner", meaning: "มุม" },
  { word: "correctly", meaning: "อย่างถูกต้อง" },
  { word: "count", meaning: "นับ, จำนวน" },
  { word: "couple", meaning: "คู่, สองคน" },
  { word: "cover", meaning: "คลุม, ปกปิด" },
  { word: "crazy", meaning: "บ้า, เพี้ยน" },
  { word: "creative", meaning: "สร้างสรรค์" },
  { word: "credit", meaning: "เครดิต, หน่วยกิต" },
  { word: "crime", meaning: "อาชญากรรม" },
  { word: "criminal", meaning: "อาชญากร, ผิดกฎหมาย" },
  { word: "cross", meaning: "ข้าม, กากบาท" },
  { word: "crowd", meaning: "ฝูงชน" },
  { word: "crowded", meaning: "แออัด" },
  { word: "cry", meaning: "ร้องไห้, ตะโกน" },
  { word: "cupboard", meaning: "ตู้เก็บของ, ตู้กับข้าว" },
  { word: "curly", meaning: "หยิก, เป็นลอน" },
  { word: "cycle", meaning: "วงจร, ขี่จักรยาน" },
  { word: "daily", meaning: "รายวัน, ทุกวัน" },
  { word: "danger", meaning: "อันตราย" },
  { word: "dark", meaning: "มืด, มืดมน" },
  { word: "data", meaning: "ข้อมูล" },
  { word: "dead", meaning: "ตาย, ไม่มีชีวิต" },
  { word: "deal", meaning: "จัดการ, ข้อตกลง" },
  { word: "dear", meaning: "ที่รัก, แพง" },
  { word: "death", meaning: "ความตาย" },
  { word: "decision", meaning: "การตัดสินใจ" },
  { word: "deep", meaning: "ลึก, ละเอียด" },
  { word: "definitely", meaning: "แน่นอน" },
  { word: "degree", meaning: "ระดับ, ปริญญา" },
  { word: "dentist", meaning: "ทันตแพทย์" },
  { word: "department", meaning: "แผนก, กรม" },
  { word: "depend", meaning: "ขึ้นอยู่กับ" },
  { word: "desert", meaning: "ทะเลทราย, ทอดทิ้ง" },
  { word: "designer", meaning: "นักออกแบบ" },
  { word: "destroy", meaning: "ทำลาย" },
  { word: "detective", meaning: "นักสืบ" },
  { word: "develop", meaning: "พัฒนา, เติบโต" },
  { word: "device", meaning: "อุปกรณ์" },
  { word: "diary", meaning: "บันทึกประจำวัน" },
  { word: "differently", meaning: "แตกต่างกัน" },
  { word: "digital", meaning: "ดิจิทัล, เชิงตัวเลข" },
  { word: "direct", meaning: "โดยตรง, กำกับ" },
  { word: "direction", meaning: "ทิศทาง, แนวทาง" },
  { word: "director", meaning: "ผู้อำนวยการ, ผู้กำกับ" },
  { word: "disagree", meaning: "ไม่เห็นด้วย" },
  { word: "disappear", meaning: "หายไป" },
  { word: "disaster", meaning: "ภัยพิบัติ, หายนะ" },
  { word: "discover", meaning: "ค้นพบ" },
  { word: "discovery", meaning: "การค้นพบ" },
  { word: "discussion", meaning: "การสนทนา, การอภิปราย" },
  { word: "disease", meaning: "โรค" },
  { word: "distance", meaning: "ระยะทาง, ระยะห่าง" },
  { word: "divorced", meaning: "หย่าร้าง" },
  { word: "document", meaning: "เอกสาร, บันทึก" },
  { word: "double", meaning: "สองเท่า, คู่" },
  { word: "download", meaning: "ดาวน์โหลด" },
  { word: "downstairs", meaning: "ชั้นล่าง, ข้างล่าง" },
  { word: "drama", meaning: "ละคร, ดราม่า" },
  { word: "drawing", meaning: "ภาพวาด, การวาด" },
  { word: "dream", meaning: "ฝัน, ความฝัน" },
  { word: "drive", meaning: "ขับรถ, ขับเคลื่อน" },
  { word: "driving", meaning: "การขับรถ, การขับเคลื่อน" },
  { word: "drop", meaning: "ปล่อย, ลดลง" },
  { word: "drug", meaning: "ยา, สารเสพติด" },
  { word: "dry", meaning: "แห้ง, ทำให้แห้ง" },
  { word: "earn", meaning: "หาเงิน, ได้รับ" },
  { word: "earth", meaning: "โลก, ดิน" },
  { word: "easily", meaning: "อย่างง่ายดาย, ได้ง่าย" },
  { word: "education", meaning: "การศึกษา" },
  { word: "effect", meaning: "ผลกระทบ, ผลลัพธ์" },
  { word: "either", meaning: "อย่างใดอย่างหนึ่ง, ทั้งสอง" },
  { word: "electric", meaning: "ไฟฟ้า, ใช้ไฟฟ้า" },
  { word: "electrical", meaning: "เกี่ยวกับไฟฟ้า" },
  { word: "electricity", meaning: "ไฟฟ้า" },
  { word: "electronic", meaning: "อิเล็กทรอนิกส์" },
  { word: "employ", meaning: "จ้างงาน" },
  { word: "employee", meaning: "ลูกจ้าง, พนักงาน" },
  { word: "employer", meaning: "นายจ้าง" },
  { word: "empty", meaning: "ว่าง, เปล่า" },
  { word: "ending", meaning: "ตอนจบ, สิ้นสุด" },
  { word: "energy", meaning: "พลังงาน, พลัง" },
  { word: "engine", meaning: "เครื่องยนต์" },
  { word: "engineer", meaning: "วิศวกร" },
  { word: "enormous", meaning: "มหึมา, ใหญ่โต" },
  { word: "enter", meaning: "เข้า, เข้ามา" },
  { word: "environment", meaning: "สิ่งแวดล้อม" },
  { word: "equipment", meaning: "อุปกรณ์" },
  { word: "error", meaning: "ข้อผิดพลาด" },
  { word: "especially", meaning: "โดยเฉพาะ, โดยเฉพาะอย่างยิ่ง" },
  { word: "essay", meaning: "เรียงความ, บทความ" },
  { word: "everyday", meaning: "ทุกวัน, ธรรมดา" },
  { word: "everywhere", meaning: "ทุกที่" },
  { word: "evidence", meaning: "หลักฐาน" },
  { word: "exact", meaning: "แม่นยำ, ถูกต้อง" },
  { word: "exactly", meaning: "อย่างแน่นอน, เป๊ะ" },
  { word: "excellent", meaning: "ยอดเยี่ยม, ดีเลิศ" },
  { word: "except", meaning: "ยกเว้น, นอกจาก" },
  { word: "exist", meaning: "มีอยู่" },
  { word: "expect", meaning: "คาดหวัง, คาดการณ์" },
  { word: "experience", meaning: "ประสบการณ์, พบ" },
  { word: "experiment", meaning: "การทดลอง, ทดลอง" },
  { word: "expert", meaning: "ผู้เชี่ยวชาญ" },
  { word: "explanation", meaning: "คำอธิบาย" },
  { word: "express", meaning: "แสดงออก, ด่วน" },
  { word: "expression", meaning: "การแสดงออก, สำนวน" },
  { word: "extreme", meaning: "สุดขั้ว, รุนแรง" },
  { word: "extremely", meaning: "อย่างยิ่ง, มาก" },
  { word: "factor", meaning: "ปัจจัย" },
  { word: "factory", meaning: "โรงงาน" },
  { word: "fail", meaning: "ล้มเหลว, สอบตก" },
  { word: "fair", meaning: "ยุติธรรม, งานแฟร์" },
  { word: "fall", meaning: "ตก, ร่วง" },
  { word: "fan", meaning: "พัดลม, แฟนคลับ" },
  { word: "farm", meaning: "ฟาร์ม, ทำฟาร์ม" },
  { word: "farming", meaning: "การทำฟาร์ม, การเกษตร" },
  { word: "fashion", meaning: "แฟชั่น, แนวโน้ม" },
  { word: "fat", meaning: "อ้วน, ไขมัน" },
  { word: "fear", meaning: "ความกลัว, กลัว" },
  { word: "feature", meaning: "ลักษณะเด่น, คุณสมบัติ" },
  { word: "feed", meaning: "ให้อาหาร, อาหาร" },
  { word: "female", meaning: "เพศหญิง, หญิง" },
  { word: "fiction", meaning: "นิยาย, เรื่องแต่ง" },
  { word: "field", meaning: "ทุ่ง, สนาม, สาขา" },
  { word: "fight", meaning: "ต่อสู้, การต่อสู้" },
  { word: "figure", meaning: "ตัวเลข, บุคคล, รูปร่าง, คิด" },
  { word: "film", meaning: "หนัง, ฟิล์ม" },
  { word: "final", meaning: "สุดท้าย, รอบชิงชนะเลิศ" },
  { word: "finally", meaning: "ในที่สุด, สุดท้าย" },
  { word: "finger", meaning: "นิ้ว" },
  { word: "finish", meaning: "เสร็จ, จบ" },
  { word: "first", meaning: "แรก, อันดับหนึ่ง" },
  { word: "firstly", meaning: "อันดับแรก, ก่อนอื่น" },
  { word: "fish", meaning: "ปลา" },
  { word: "fishing", meaning: "การตกปลา" },
  { word: "fit", meaning: "เหมาะ, พอดี, แข็งแรง" },
  { word: "fix", meaning: "ซ่อม, แก้ไข" },
  { word: "flat", meaning: "แบน, อพาร์ตเมนต์" },
  { word: "flu", meaning: "ไข้หวัดใหญ่" },
  { word: "fly", meaning: "บิน, แมลงวัน" },
  { word: "flying", meaning: "บิน, การบิน" },
  { word: "focus", meaning: "จุดโฟกัส, มุ่งเน้น" },
  { word: "following", meaning: "ต่อไป, ดังต่อไปนี้" },
  { word: "foreign", meaning: "ต่างประเทศ, ต่างชาติ" },
  { word: "forest", meaning: "ป่า" },
  { word: "fork", meaning: "ส้อม, ทางแยก" },
  { word: "formal", meaning: "เป็นทางการ, พิธีการ" },
  { word: "fortunately", meaning: "โชคดีที่" },
  { word: "forward", meaning: "ไปข้างหน้า, ส่งต่อ" },
  { word: "free", meaning: "ฟรี, อิสระ" },
  { word: "fresh", meaning: "สด, ใหม่" },
  { word: "fridge", meaning: "ตู้เย็น" },
  { word: "frog", meaning: "กบ" },
  { word: "fun", meaning: "สนุก, ความสนุก" },
  { word: "furniture", meaning: "เฟอร์นิเจอร์" },
  { word: "further", meaning: "เพิ่มเติม, ไกลกว่า" },
  { word: "future", meaning: "อนาคต" },
  { word: "gallery", meaning: "แกลเลอรี, ห้องจัดแสดง" },
  { word: "gap", meaning: "ช่องว่าง, ความแตกต่าง" },
  { word: "gas", meaning: "แก๊ส, น้ำมันเชื้อเพลิง" },
  { word: "gate", meaning: "ประตู, ทางเข้า" },
  { word: "general", meaning: "ทั่วไป, นายพล" },
  { word: "gift", meaning: "ของขวัญ, พรสวรรค์" },
  { word: "goal", meaning: "เป้าหมาย, ประตู" },
  { word: "god", meaning: "พระเจ้า, เทพเจ้า" },
  { word: "gold", meaning: "ทองคำ, สีทอง" },
  { word: "golf", meaning: "กอล์ฟ" },
  { word: "good", meaning: "ดี" },
  { word: "government", meaning: "รัฐบาล" },
  { word: "grass", meaning: "หญ้า" },
  { word: "greet", meaning: "ทักทาย, ต้อนรับ" },
  { word: "ground", meaning: "พื้น, พื้นดิน, เหตุผล" },
  { word: "guest", meaning: "แขก, ผู้มาเยือน" },
  { word: "guide", meaning: "ผู้นำทาง, นำทาง" },
  { word: "gun", meaning: "ปืน" },
  { word: "guy", meaning: "ผู้ชาย, คน" },
  { word: "habit", meaning: "นิสัย" },
  { word: "half", meaning: "ครึ่ง" },
  { word: "hall", meaning: "ห้องโถง" },
  { word: "happily", meaning: "อย่างมีความสุข" },
  { word: "have", meaning: "มี" },
  { word: "headache", meaning: "ปวดหัว" },
  { word: "heart", meaning: "หัวใจ, ใจ" },
  { word: "heat", meaning: "ความร้อน, ร้อน" },
  { word: "heavy", meaning: "หนัก" },
  { word: "height", meaning: "ความสูง" },
  { word: "helpful", meaning: "เป็นประโยชน์, ช่วยเหลือ" },
  { word: "hero", meaning: "วีรบุรุษ, ฮีโร่" },
  { word: "hers", meaning: "ของเธอ" },
  { word: "herself", meaning: "ตัวเธอเอง" },
  { word: "hide", meaning: "ซ่อน, หนังสัตว์" },
  { word: "high", meaning: "สูง" },
  { word: "hill", meaning: "เนินเขา, เนิน" },
  { word: "himself", meaning: "ตัวเขาเอง" },
  { word: "his", meaning: "ของเขา" },
  { word: "hit", meaning: "ตี, ชน" },
  { word: "hockey", meaning: "ฮอกกี้" },
  { word: "hold", meaning: "ถือ, จับ" },
  { word: "hole", meaning: "รู, หลุม" },
  { word: "home", meaning: "บ้าน, ที่บ้าน" },
  { word: "hope", meaning: "หวัง" },
  { word: "huge", meaning: "ใหญ่โต, มหึมา" },
  { word: "human", meaning: "มนุษย์" },
  { word: "hurt", meaning: "เจ็บ, ทำให้เจ็บ" },
  { word: "ideal", meaning: "อุดมคติ" },
  { word: "identify", meaning: "ระบุ, ระบุตัวตน" },
  { word: "ill", meaning: "ป่วย" },
  { word: "illness", meaning: "โรค, ความเจ็บป่วย" },
  { word: "image", meaning: "ภาพ, รูปภาพ" },
  { word: "immediately", meaning: "ทันที" },
  { word: "impossible", meaning: "เป็นไปไม่ได้" },
  { word: "included", meaning: "รวมอยู่" },
  { word: "including", meaning: "รวมถึง" },
  { word: "increase", meaning: "เพิ่ม, การเพิ่ม" },
  { word: "incredible", meaning: "น่าเหลือเชื่อ, ยอดเยี่ยม" },
  { word: "independent", meaning: "อิสระ" },
  { word: "individual", meaning: "บุคคล, แต่ละคน" },
  { word: "industry", meaning: "อุตสาหกรรม" },
  { word: "informal", meaning: "ไม่เป็นทางการ" },
  { word: "injury", meaning: "การบาดเจ็บ" },
  { word: "insect", meaning: "แมลง" },
  { word: "inside", meaning: "ข้างใน, ภายใน" },
  { word: "instruction", meaning: "คำสั่ง, คำแนะนำ" },
  { word: "instructor", meaning: "ผู้สอน, ครูฝึก" },
  { word: "instrument", meaning: "เครื่องมือ, เครื่องดนตรี" },
  { word: "intelligent", meaning: "ฉลาด" },
  { word: "international", meaning: "ระหว่างประเทศ" },
  { word: "introduction", meaning: "การแนะนำ, บทนำ" },
  { word: "invent", meaning: "ประดิษฐ์, คิดค้น" },
  { word: "invention", meaning: "สิ่งประดิษฐ์" },
  { word: "invitation", meaning: "คำเชิญ" },
  { word: "invite", meaning: "เชิญ" },
  { word: "involve", meaning: "เกี่ยวข้อง, รวมถึง" },
  { word: "item", meaning: "ชิ้น, รายการ" },
  { word: "itself", meaning: "ตัวมันเอง" },
  { word: "jam", meaning: "แยม, การจราจรติดขัด" },
  { word: "jazz", meaning: "ดนตรีแจ๊ส" },
  { word: "jewellery", meaning: "เครื่องประดับ" },
  { word: "joke", meaning: "เรื่องตลก, มุก" },
  { word: "journalist", meaning: "นักข่าว" },
  { word: "jump", meaning: "กระโดด" },
  { word: "kid", meaning: "เด็ก, ล้อเล่น" },
  { word: "kill", meaning: "ฆ่า" },
  { word: "king", meaning: "กษัตริย์" },
  { word: "knee", meaning: "เข่า" },
  { word: "knife", meaning: "มีด" },
  { word: "knock", meaning: "เคาะ, เคาะประตู" },
  { word: "knowledge", meaning: "ความรู้" },
  { word: "lab", meaning: "ห้องปฏิบัติการ" },
  { word: "lady", meaning: "สุภาพสตรี" },
  { word: "lake", meaning: "ทะเลสาบ" },
  { word: "lamp", meaning: "โคมไฟ" },
  { word: "land", meaning: "ที่ดิน, ลงจอด" },
  { word: "laptop", meaning: "โน้ตบุ๊ก" },
  { word: "last1 (final)", meaning: "สุดท้าย" },
  { word: "last1 (taking time)", meaning: "คงอยู่, อยู่นาน" },
  { word: "later", meaning: "ทีหลัง, ภายหลัง" },
  { word: "laughter", meaning: "เสียงหัวเราะ" },
  { word: "law", meaning: "กฎหมาย" },
  { word: "lawyer", meaning: "ทนายความ" },
  { word: "lazy", meaning: "ขี้เกียจ" },
  { word: "lead1", meaning: "นำ, นำทาง" },
  { word: "leader", meaning: "ผู้นำ" },
  { word: "learning", meaning: "การเรียนรู้" },
  { word: "least", meaning: "น้อยที่สุด" },
  { word: "lecture", meaning: "บรรยาย, การบรรยาย" },
  { word: "lemon", meaning: "มะนาว" },
  { word: "lend", meaning: "ให้ยืม" },
  { word: "less", meaning: "น้อยกว่า" },
  { word: "level", meaning: "ระดับ, ขั้น" },
  { word: "lifestyle", meaning: "วิถีชีวิต" },
  { word: "lift", meaning: "ยกขึ้น, ลิฟต์" },
  { word: "light (from the sun/a lamp)", meaning: "แสง" },
  { word: "light (not heavy)", meaning: "เบา" },
  { word: "likely", meaning: "น่าจะ" },
  { word: "link", meaning: "เชื่อม, ความเชื่อมโยง" },
  { word: "listener", meaning: "ผู้ฟัง" },
  { word: "little", meaning: "เล็ก, น้อย" },
  { word: "lock", meaning: "ล็อก, กุญแจ" },
  { word: "look", meaning: "มอง, รูปลักษณ์" },
  { word: "lorry", meaning: "รถบรรทุก" },
  { word: "lost", meaning: "หาย, หลงทาง" },
  { word: "loud", meaning: "ดัง" },
  { word: "loudly", meaning: "อย่างดัง" },
  { word: "lovely", meaning: "น่ารัก, งดงาม" },
  { word: "low", meaning: "ต่ำ" },
  { word: "luck", meaning: "โชค" },
  { word: "lucky", meaning: "โชคดี" },
  { word: "mail", meaning: "จดหมาย, ไปรษณีย์" },
  { word: "major", meaning: "สำคัญ, ใหญ่, วิชาเอก" },
  { word: "male", meaning: "ชาย, เพศผู้" },
  { word: "manage", meaning: "จัดการ, บริหาร" },
  { word: "manager", meaning: "ผู้จัดการ" },
  { word: "manner", meaning: "วิธี, มารยาท" },
  { word: "mark", meaning: "เครื่องหมาย, คะแนน" },
  { word: "marry", meaning: "แต่งงาน" },
  { word: "material", meaning: "วัสดุ, เนื้อหา" },
  { word: "mathematics", meaning: "คณิตศาสตร์" },
  { word: "maths", meaning: "คณิตศาสตร์" },
  { word: "matter", meaning: "เรื่อง, สสาร" },
  { word: "may", meaning: "อาจจะ, พฤษภาคม" },
  { word: "media", meaning: "สื่อ, สื่อมวลชน" },
  { word: "medical", meaning: "ทางการแพทย์" },
  { word: "medicine", meaning: "ยา, เวชศาสตร์" },
  { word: "memory", meaning: "ความจำ, หน่วยความจำ" },
  { word: "mention", meaning: "กล่าวถึง, พูดถึง" },
  { word: "metal", meaning: "โลหะ" },
  { word: "method", meaning: "วิธี" },
  { word: "middle", meaning: "กลาง" },
  { word: "might", meaning: "อาจจะ, อำนาจ" },
  { word: "mind", meaning: "จิตใจ, ใส่ใจ" },
  { word: "mine (belongs to me)", meaning: "ของฉัน" },
  { word: "mirror", meaning: "กระจก" },
  { word: "missing", meaning: "หายไป, ขาดหาย" },
  { word: "mobile", meaning: "มือถือ, เคลื่อนที่" },
  { word: "monkey", meaning: "ลิง" },
  { word: "moon", meaning: "ดวงจันทร์" },
  { word: "mostly", meaning: "ส่วนใหญ่" },
  { word: "motorcycle", meaning: "รถจักรยานยนต์" },
  { word: "movement", meaning: "การเคลื่อนไหว, ขบวนการ" },
  { word: "musical", meaning: "เกี่ยวกับดนตรี, ละครเพลง" },
  { word: "musician", meaning: "นักดนตรี" },
  { word: "myself", meaning: "ฉันเอง" },
  { word: "narrow", meaning: "แคบ, จำกัด" },
  { word: "national", meaning: "แห่งชาติ" },
  { word: "nature", meaning: "ธรรมชาติ, ลักษณะ" },
  { word: "nearly", meaning: "เกือบจะ" },
  { word: "necessary", meaning: "จำเป็น" },
  { word: "neck", meaning: "คอ" },
  { word: "need", meaning: "ต้องการ, จำเป็น" },
  { word: "neither", meaning: "ไม่มีทั้งสอง" },
  { word: "nervous", meaning: "ประหม่า, วิตกกังวล" },
  { word: "network", meaning: "เครือข่าย" },
  { word: "noise", meaning: "เสียงรบกวน, เสียง" },
  { word: "noisy", meaning: "ส่งเสียงดัง, เอะอะ" },
  { word: "none", meaning: "ไม่มีเลย" },
  { word: "normal", meaning: "ปกติ" },
  { word: "normally", meaning: "โดยปกติ" },
  { word: "notice", meaning: "สังเกต, ประกาศ" },
  { word: "novel", meaning: "นวนิยาย" },
  { word: "nowhere", meaning: "ไม่มีที่ไหน" },
  { word: "number", meaning: "จำนวน, เลข" },
  { word: "nut", meaning: "ถั่ว, น็อต" },
  { word: "ocean", meaning: "มหาสมุทร, ทะเล" },
  { word: "offer", meaning: "เสนอ, ข้อเสนอ" },
  { word: "officer", meaning: "เจ้าหน้าที่, นายทหาร" },
  { word: "oil", meaning: "น้ำมัน" },
  { word: "onto", meaning: "ขึ้นบน, บน" },
  { word: "opportunity", meaning: "โอกาส" },
  { word: "option", meaning: "ตัวเลือก" },
  { word: "ordinary", meaning: "ธรรมดา, ปกติ" },
  { word: "organization", meaning: "องค์กร" },
  { word: "organize", meaning: "จัด, จัดระเบียบ" },
  { word: "original", meaning: "ดั้งเดิม, ต้นฉบับ" },
  { word: "ourselves", meaning: "พวกเราเอง" },
  { word: "outside", meaning: "ภายนอก, ข้างนอก" },
  { word: "oven", meaning: "เตาอบ" },
  { word: "own", meaning: "เป็นเจ้าของ, ของตนเอง" },
  { word: "owner", meaning: "เจ้าของ" },
  { word: "pack", meaning: "ห่อ, บรรจุ" },
  { word: "pain", meaning: "ความเจ็บปวด, ปวด" },
  { word: "painter", meaning: "จิตรกร, ช่างทาสี" },
  { word: "palace", meaning: "พระราชวัง" },
  { word: "pants", meaning: "กางเกง" },
  { word: "parking", meaning: "ที่จอดรถ" },
  { word: "particular", meaning: "เฉพาะ, เจาะจง" },
  { word: "pass", meaning: "ผ่าน" },
  { word: "passenger", meaning: "ผู้โดยสาร" },
  { word: "past", meaning: "อดีต" },
  { word: "patient", meaning: "คนไข้, อดทน" },
  { word: "pattern", meaning: "รูปแบบ, ลวดลาย" },
  { word: "pay", meaning: "จ่าย, ชำระ" },
  { word: "peace", meaning: "สันติภาพ, ความสงบ" },
  { word: "penny", meaning: "เพนนี" },
  { word: "per", meaning: "ต่อ" },
  { word: "per cent", meaning: "เปอร์เซ็นต์" },
  { word: "perform", meaning: "แสดง, ปฏิบัติ" },
  { word: "perhaps", meaning: "อาจจะ" },
  { word: "permission", meaning: "การอนุญาต, ใบอนุญาต" },
  { word: "personality", meaning: "บุคลิกภาพ" },
  { word: "pet", meaning: "สัตว์เลี้ยง" },
  { word: "petrol", meaning: "น้ำมันเบนซิน" },
  { word: "photograph", meaning: "ภาพถ่าย, ถ่ายรูป" },
  { word: "physical", meaning: "ทางร่างกาย, กายภาพ" },
  { word: "physics", meaning: "ฟิสิกส์" },
  { word: "pick", meaning: "เลือก, หยิบ" },
  { word: "pilot", meaning: "นักบิน, นำร่อง" },
  { word: "planet", meaning: "ดาวเคราะห์" },
  { word: "plant", meaning: "พืช, โรงงาน" },
  { word: "plastic", meaning: "พลาสติก" },
  { word: "plate", meaning: "จาน, แผ่น" },
  { word: "platform", meaning: "ชานชาลา, แพลตฟอร์ม" },
  { word: "please", meaning: "กรุณา, โปรด" },
  { word: "pleased", meaning: "พอใจ, ยินดี" },
  { word: "pocket", meaning: "กระเป๋า, ช่องใส่ของ" },
  { word: "polite", meaning: "สุภาพ" },
  { word: "pollution", meaning: "มลพิษ" },
  { word: "pop", meaning: "เพลงป็อป, แตก" },
  { word: "population", meaning: "ประชากร" },
  { word: "position", meaning: "ตำแหน่ง, ที่ตั้ง" },
  { word: "possession", meaning: "ทรัพย์สิน, การครอบครอง" },
  { word: "possibility", meaning: "ความเป็นไปได้" },
  { word: "poster", meaning: "โปสเตอร์" },
  { word: "power", meaning: "อำนาจ, พลัง" },
  { word: "predict", meaning: "ทำนาย, คาดการณ์" },
  { word: "present", meaning: "ปัจจุบัน, นำเสนอ, ของขวัญ" },
  { word: "president", meaning: "ประธานาธิบดี, ประธาน" },
  { word: "prevent", meaning: "ป้องกัน, ขัดขวาง" },
  { word: "print", meaning: "พิมพ์, สิ่งพิมพ์" },
  { word: "printer", meaning: "เครื่องพิมพ์" },
  { word: "prison", meaning: "คุก, เรือนจำ" },
  { word: "prize", meaning: "รางวัล" },
  { word: "process", meaning: "กระบวนการ, ประมวลผล" },
  { word: "produce", meaning: "ผลิต, ผลผลิต" },
  { word: "professional", meaning: "มืออาชีพ, วิชาชีพ" },
  { word: "professor", meaning: "ศาสตราจารย์" },
  { word: "profile", meaning: "โปรไฟล์, ประวัติย่อ" },
  { word: "program", meaning: "โปรแกรม, โครงการ" },
  { word: "progress", meaning: "ความก้าวหน้า, ก้าวหน้า" },
  { word: "promise", meaning: "สัญญา, ให้คำมั่น" },
  { word: "pronounce", meaning: "ออกเสียง" },
  { word: "protect", meaning: "ปกป้อง, คุ้มครอง" },
  { word: "provide", meaning: "ให้, จัดหา" },
  { word: "pub", meaning: "ผับ" },
  { word: "public", meaning: "สาธารณะ" },
  { word: "publish", meaning: "ตีพิมพ์, เผยแพร่" },
  { word: "pull", meaning: "ดึง, ลาก" },
  { word: "purpose", meaning: "วัตถุประสงค์" },
  { word: "push", meaning: "ผลัก, ดัน" },
  { word: "quality", meaning: "คุณภาพ" },
  { word: "quantity", meaning: "ปริมาณ" },
  { word: "queen", meaning: "ราชินี" },
  { word: "question", meaning: "คำถาม" },
  { word: "quietly", meaning: "อย่างเงียบๆ" },
  { word: "race (competition)", meaning: "การแข่งขัน" },
  { word: "railway", meaning: "ทางรถไฟ" },
  { word: "raise", meaning: "ยกขึ้น, เพิ่ม" },
  { word: "rate", meaning: "อัตรา, ให้คะแนน" },
  { word: "rather", meaning: "ค่อนข้าง" },
  { word: "reach", meaning: "ไปถึง, ติดต่อ" },
  { word: "react", meaning: "ตอบสนอง" },
  { word: "realize", meaning: "ตระหนัก, รู้ตัว" },
  { word: "receive", meaning: "ได้รับ" },
  { word: "recent", meaning: "ล่าสุด" },
  { word: "recently", meaning: "เมื่อเร็วๆ นี้" },
  { word: "reception", meaning: "การต้อนรับ, แผนกรับแขก" },
  { word: "recipe", meaning: "สูตรอาหาร" },
  { word: "recognize", meaning: "จำได้, ยอมรับ" },
  { word: "recommend", meaning: "แนะนำ" },
  { word: "record", meaning: "บันทึก, ระเบียน" },
  { word: "recording", meaning: "การบันทึก, บันทึกเสียง" },
  { word: "recycle", meaning: "รีไซเคิล, นำกลับมาใช้ใหม่" },
  { word: "reduce", meaning: "ลด" },
  { word: "refer", meaning: "อ้างอิง, ส่งต่อ" },
  { word: "refuse1", meaning: "ขยะ" },
  { word: "region", meaning: "ภูมิภาค, เขต" },
  { word: "regular", meaning: "ปกติ, ประจำ" },
  { word: "relationship", meaning: "ความสัมพันธ์" },
  { word: "remove", meaning: "เอาออก, ลบ" },
  { word: "repair", meaning: "ซ่อม" },
  { word: "replace", meaning: "แทนที่, เปลี่ยน" },
  { word: "reply", meaning: "ตอบ, ตอบกลับ" },
  { word: "report", meaning: "รายงาน, แจ้ง" },
  { word: "reporter", meaning: "นักข่าว" },
  { word: "request", meaning: "ขอ, คำขอ" },
  { word: "research", meaning: "วิจัย, การวิจัย" },
  { word: "researcher", meaning: "นักวิจัย" },
  { word: "respond", meaning: "ตอบ, ตอบสนอง" },
  { word: "response", meaning: "การตอบสนอง, คำตอบ" },
  { word: "rest (remaining part)", meaning: "ที่เหลือ, ส่วนที่เหลือ" },
  { word: "rest (sleep/relax)", meaning: "พักผ่อน, พัก" },
  { word: "review", meaning: "ทบทวน, รีวิว" },
  { word: "ride", meaning: "นั่ง, ขี่" },
  { word: "ring1", meaning: "แหวน" },
  { word: "ring2", meaning: "โทร, เสียงกริ่ง" },
  { word: "rise", meaning: "ขึ้น, เพิ่มขึ้น" },
  { word: "rock (stone)", meaning: "ก้อนหิน" },
  { word: "rock (music)", meaning: "เพลงร็อก" },
  { word: "role", meaning: "บทบาท" },
  { word: "roof", meaning: "หลังคา" },
  { word: "round", meaning: "รอบ, กลม" },
  { word: "route", meaning: "เส้นทาง" },
  { word: "rubbish", meaning: "ขยะ, ไร้สาระ" },
  { word: "rude", meaning: "หยาบคาย" },
  { word: "run", meaning: "วิ่ง, ดำเนิน" },
  { word: "runner", meaning: "นักวิ่ง" },
  { word: "running", meaning: "การวิ่ง, กำลังวิ่ง" },
  { word: "sadly", meaning: "อย่างน่าเศร้า" },
  { word: "safe", meaning: "ปลอดภัย" },
  { word: "sail", meaning: "แล่นเรือ, ใบเรือ" },
  { word: "sailing", meaning: "การแล่นเรือ" },
  { word: "salary", meaning: "เงินเดือน" },
  { word: "sale", meaning: "การขาย, ลดราคา" },
  { word: "sauce", meaning: "ซอส" },
  { word: "save", meaning: "ช่วยเหลือ, บันทึก, ประหยัด" },
  { word: "scared", meaning: "กลัว" },
  { word: "scary", meaning: "น่ากลัว" },
  { word: "scene", meaning: "ฉาก, เหตุการณ์" },
  { word: "schedule", meaning: "ตารางเวลา, กำหนดการ" },
  { word: "score", meaning: "คะแนน, เพลงประกอบ" },
  { word: "screen", meaning: "จอ, กรอง" },
  { word: "search", meaning: "ค้นหา" },
  { word: "season", meaning: "ฤดูกาล" },
  { word: "seat", meaning: "ที่นั่ง" },
  { word: "second1 (next after the first)", meaning: "ที่สอง" },
  { word: "secondly", meaning: "ประการที่สอง" },
  { word: "secret", meaning: "ลับ, ความลับ" },
  { word: "secretary", meaning: "เลขานุการ" },
  { word: "seem", meaning: "ดูเหมือน" },
  { word: "sense", meaning: "ความรู้สึก, ความหมาย" },
  { word: "separate", meaning: "แยก, แยกออก" },
  { word: "series", meaning: "ชุด, ละครชุด" },
  { word: "serious", meaning: "จริงจัง, ร้ายแรง" },
  { word: "serve", meaning: "ให้บริการ, เสิร์ฟ" },
  { word: "service", meaning: "บริการ, งานบริการ" },
  { word: "several", meaning: "หลาย" },
  { word: "shake", meaning: "เขย่า, สั่น" },
  { word: "shall", meaning: "จะ" },
  { word: "shape", meaning: "รูปร่าง, รูปทรง" },
  { word: "sheet", meaning: "แผ่น, ผ้าปูที่นอน" },
  { word: "ship", meaning: "เรือ, ส่งสินค้า" },
  { word: "shoulder", meaning: "ไหล่" },
  { word: "shout", meaning: "ตะโกน" },
  { word: "shut", meaning: "ปิด" },
  { word: "side", meaning: "ข้าง, ด้าน" },
  { word: "sign", meaning: "สัญลักษณ์, ลงชื่อ" },
  { word: "silver", meaning: "เงิน, สีเงิน" },
  { word: "simple", meaning: "ง่าย, เรียบง่าย" },
  { word: "since", meaning: "ตั้งแต่, เนื่องจาก" },
  { word: "singing", meaning: "ร้องเพลง" },
  { word: "single", meaning: "เดี่ยว, โสด" },
  { word: "sir", meaning: "คุณ, ท่าน" },
  { word: "site", meaning: "ที่ตั้ง, เว็บไซต์" },
  { word: "size", meaning: "ขนาด" },
  { word: "ski", meaning: "สกี, เล่นสกี" },
  { word: "skiing", meaning: "เล่นสกี" },
  { word: "skin", meaning: "ผิว, หนัง" },
  { word: "sky", meaning: "ท้องฟ้า" },
  { word: "sleep", meaning: "นอนหลับ, การนอน" },
  { word: "slowly", meaning: "ช้าๆ" },
  { word: "smartphone", meaning: "สมาร์ทโฟน" },
  { word: "smell", meaning: "กลิ่น, ดม" },
  { word: "smile", meaning: "ยิ้ม, รอยยิ้ม" },
  { word: "smoke", meaning: "ควัน, สูบ" },
  { word: "smoking", meaning: "การสูบบุหรี่" },
  { word: "soap", meaning: "สบู่" },
  { word: "soccer", meaning: "ฟุตบอล" },
  { word: "social", meaning: "สังคม, ทางสังคม" },
  { word: "society", meaning: "สังคม, สมาคม" },
  { word: "sock", meaning: "ถุงเท้า" },
  { word: "soft", meaning: "นุ่ม, อ่อน" },
  { word: "soldier", meaning: "ทหาร" },
  { word: "solution", meaning: "วิธีแก้, สารละลาย" },
  { word: "solve", meaning: "แก้ปัญหา, หาคำตอบ" },
  { word: "somewhere", meaning: "ที่ไหนสักแห่ง" },
  { word: "sort", meaning: "ประเภท, จัดประเภท" },
  { word: "source", meaning: "แหล่ง, ต้นกำเนิด" },
  { word: "speaker", meaning: "ลำโพง, ผู้พูด" },
  { word: "specific", meaning: "เฉพาะ, โดยเฉพาะ" },
  { word: "speech", meaning: "คำพูด, สุนทรพจน์" },
  { word: "speed", meaning: "ความเร็ว" },
  { word: "spider", meaning: "แมงมุม" },
  { word: "spoon", meaning: "ช้อน" },
  { word: "square", meaning: "จัตุรัส, ลาน" },
  { word: "stage", meaning: "เวที, ระยะ" },
  { word: "stair", meaning: "ขั้นบันได" },
  { word: "stamp", meaning: "แสตมป์, ประทับตรา" },
  { word: "star", meaning: "ดาว" },
  { word: "start", meaning: "เริ่ม, จุดเริ่มต้น" },
  { word: "state", meaning: "รัฐ, สถานะ" },
  { word: "stay", meaning: "อยู่, พัก" },
  { word: "steal", meaning: "ขโมย" },
  { word: "step", meaning: "ก้าว, ขั้นตอน" },
  { word: "stomach", meaning: "ท้อง, กระเพาะอาหาร" },
  { word: "stone", meaning: "หิน, ก้อนหิน" },
  { word: "store", meaning: "ร้านค้า, เก็บ" },
  { word: "storm", meaning: "พายุ" },
  { word: "straight", meaning: "ตรง, ซื่อตรง" },
  { word: "strange", meaning: "แปลก, ประหลาด" },
  { word: "strategy", meaning: "กลยุทธ์, ยุทธศาสตร์" },
  { word: "stress", meaning: "ความเครียด, เน้น" },
  { word: "structure", meaning: "โครงสร้าง, แบบแผน" },
  { word: "stupid", meaning: "โง่, โง่งม" },
  { word: "succeed", meaning: "ประสบความสำเร็จ" },
  { word: "successful", meaning: "ประสบความสำเร็จ, สำเร็จ" },
  { word: "such", meaning: "เช่นนั้น, อย่างนั้น" },
  { word: "suddenly", meaning: "อย่างกะทันหัน, ทันที" },
  { word: "suggest", meaning: "เสนอ, แนะนำ" },
  { word: "suggestion", meaning: "ข้อเสนอ, คำแนะนำ" },
  { word: "suit", meaning: "ชุด, เหมาะ" },
  { word: "support", meaning: "สนับสนุน, ช่วยเหลือ" },
  { word: "suppose", meaning: "คิดว่า, สมมติ" },
  { word: "sure", meaning: "แน่นอน, มั่นใจ" },
  { word: "surprise", meaning: "ความประหลาดใจ, ทำให้ประหลาดใจ" },
  { word: "surprised", meaning: "ประหลาดใจ, ตกใจ" },
  { word: "surprising", meaning: "น่าประหลาดใจ, น่าตกใจ" },
  { word: "survey", meaning: "การสำรวจ, สำรวจ" },
  { word: "sweet", meaning: "หวาน, น่ารัก" },
  { word: "symbol", meaning: "สัญลักษณ์, เครื่องหมาย" },
  { word: "system", meaning: "ระบบ, ระบอบ" },
  { word: "tablet", meaning: "แท็บเล็ต, ยาเม็ด" },
  { word: "talk", meaning: "คุย, พูด" },
  { word: "target", meaning: "เป้าหมาย, เป้า" },
  { word: "task", meaning: "งาน, ภารกิจ" },
  { word: "taste", meaning: "รส, ชิม" },
  { word: "teaching", meaning: "การสอน, การถ่ายทอด" },
  { word: "technology", meaning: "เทคโนโลยี, เทคนิค" },
  { word: "teenage", meaning: "วัยรุ่น" },
  { word: "temperature", meaning: "อุณหภูมิ, ความร้อน" },
  { word: "term", meaning: "คำ, ระยะเวลา, ภาคการศึกษา" },
  { word: "text", meaning: "ข้อความ, ต้นฉบับ" },
  { word: "themselves", meaning: "พวกเขาเอง, ตัวเอง" },
  { word: "thick", meaning: "หนา, หนาทึบ" },
  { word: "thief", meaning: "ขโมย, โจร" },
  { word: "thin", meaning: "ผอม, บาง" },
  { word: "thinking", meaning: "ความคิด, การคิด" },
  { word: "third", meaning: "ที่สาม, ลำดับสาม" },
  { word: "thought", meaning: "ความคิด, ความเห็น" },
  { word: "throw", meaning: "ขว้าง, โยน" },
  { word: "tidy", meaning: "เป็นระเบียบ, เก็บกวาด" },
  { word: "tie", meaning: "เนคไท, ผูก, เสมอกัน" },
  { word: "tip", meaning: "เคล็ดลับ, ปลาย, ค่าทิป" },
  { word: "tool", meaning: "เครื่องมือ" },
  { word: "top", meaning: "บน, ยอด" },
  { word: "touch", meaning: "สัมผัส, แตะ" },
  { word: "tour", meaning: "ท่องเที่ยว, ทัวร์" },
  { word: "tourism", meaning: "การท่องเที่ยว" },
  { word: "towards", meaning: "ไปยัง, มุ่งสู่" },
  { word: "towel", meaning: "ผ้าเช็ดตัว" },
  { word: "tower", meaning: "หอคอย, ตึกสูง" },
  { word: "toy", meaning: "ของเล่น" },
  { word: "track", meaning: "เส้นทาง, ติดตาม" },
  { word: "tradition", meaning: "ประเพณี" },
  { word: "traditional", meaning: "แบบดั้งเดิม" },
  { word: "train", meaning: "รถไฟ, ฝึก" },
  { word: "trainer", meaning: "ผู้ฝึกสอน, เทรนเนอร์" },
  { word: "training", meaning: "การฝึก" },
  { word: "transport", meaning: "การขนส่ง, ขนส่ง" },
  { word: "traveller", meaning: "นักเดินทาง" },
  { word: "trouble", meaning: "ปัญหา, ความยุ่งยาก" },
  { word: "truck", meaning: "รถบรรทุก" },
  { word: "twin", meaning: "ฝาแฝด" },
  { word: "typical", meaning: "ปกติ, โดยทั่วไป" },
  { word: "underground", meaning: "ใต้ดิน, รถไฟใต้ดิน" },
  { word: "understanding", meaning: "ความเข้าใจ" },
  { word: "unfortunately", meaning: "น่าเสียดาย" },
  { word: "unhappy", meaning: "ไม่สุข, เศร้า" },
  { word: "uniform", meaning: "เครื่องแบบ" },
  { word: "unit", meaning: "หน่วย" },
  { word: "united", meaning: "รวมกัน" },
  { word: "unusual", meaning: "ไม่ธรรมดา, ผิดปกติ" },
  { word: "upstairs", meaning: "ชั้นบน, ข้างบน" },
  { word: "use", meaning: "ใช้" },
  { word: "used to", meaning: "เคย" },
  { word: "user", meaning: "ผู้ใช้" },
  { word: "usual", meaning: "ปกติ" },
  { word: "valley", meaning: "หุบเขา" },
  { word: "van", meaning: "รถตู้" },
  { word: "variety", meaning: "ความหลากหลาย, หลายชนิด" },
  { word: "vehicle", meaning: "ยานพาหนะ" },
  { word: "view", meaning: "มุมมอง, วิว" },
  { word: "virus", meaning: "ไวรัส" },
  { word: "voice", meaning: "เสียง" },
  { word: "wait", meaning: "รอ" },
  { word: "war", meaning: "สงคราม" },
  { word: "wash", meaning: "ล้าง" },
  { word: "washing", meaning: "การซัก, การล้าง" },
  { word: "wave", meaning: "โบกมือ, คลื่น" },
  { word: "weak", meaning: "อ่อนแอ" },
  { word: "web", meaning: "เว็บ, ใยแมงมุม" },
  { word: "wedding", meaning: "งานแต่งงาน" },
  { word: "weight", meaning: "น้ำหนัก" },
  { word: "welcome", meaning: "ยินดีต้อนรับ" },
  { word: "wet", meaning: "เปียก" },
  { word: "wheel", meaning: "ล้อ" },
  { word: "while", meaning: "ขณะที่, ช่วงเวลา" },
  { word: "whole", meaning: "ทั้งหมด, ทั้ง" },
  { word: "whose", meaning: "ของใคร" },
  { word: "wide", meaning: "กว้าง" },
  { word: "wild", meaning: "ป่า, ดุร้าย" },
  { word: "wind1", meaning: "ลม" },
  { word: "winner", meaning: "ผู้ชนะ" },
  { word: "wish", meaning: "ปรารถนา, อธิษฐาน" },
  { word: "wood", meaning: "ไม้" },
  { word: "wooden", meaning: "ทำจากไม้" },
  { word: "working", meaning: "ทำงาน" },
  { word: "worried", meaning: "กังวล" },
  { word: "worry", meaning: "กังวล, ความกังวล" },
  { word: "worse", meaning: "แย่กว่า" },
  { word: "worst", meaning: "แย่ที่สุด" },
  { word: "wow", meaning: "ว้าว" },
  { word: "yet", meaning: "ยัง, แต่" },
  { word: "yours", meaning: "ของคุณ" },
  { word: "zero", meaning: "ศูนย์" }
];