// ==========================================================
// คลังคำศัพท์ English B2
// ==========================================================
window.flashVocabDataEnB2 = [
{ word:"abandon", meaning:"ละทิ้ง, ทอดทิ้ง" },
{ word:"absolute", meaning:"สมบูรณ์, แน่นอน" },
{ word:"academic", meaning:"ทางวิชาการ" },
{ word:"acceptable", meaning:"ยอมรับได้" },
{ word:"accompany", meaning:"ไปด้วย, ติดตาม" },
{ word:"account", meaning:"บัญชี, บัญชีผู้ใช้" },
{ word:"accurate", meaning:"แม่นยำ, ถูกต้อง" },
{ word:"accuse", meaning:"กล่าวหา" },
{ word:"acknowledge", meaning:"ยอมรับ" },
{ word:"acquire", meaning:"ได้รับ, ได้มา" },
{ word:"actual", meaning:"จริง, ที่แท้จริง" },
{ word:"adapt", meaning:"ปรับตัว" },
{ word:"additional", meaning:"เพิ่มเติม" },
{ word:"address", meaning:"ที่อยู่, กล่าวถึง" },
{ word:"administration", meaning:"การบริหาร" },
{ word:"adopt", meaning:"รับมาใช้" },
{ word:"advance", meaning:"ก้าวหน้า" },
{ word:"affair", meaning:"เรื่อง, กิจการ" },
{ word:"afterwards", meaning:"ภายหลัง" },
{ word:"agency", meaning:"หน่วยงาน" },
{ word:"agenda", meaning:"วาระ" },
{ word:"aggressive", meaning:"ก้าวร้าว" },
{ word:"aid", meaning:"ช่วยเหลือ" },
{ word:"aircraft", meaning:"อากาศยาน" },
{ word:"alarm", meaning:"สัญญาณเตือน" },
{ word:"alter", meaning:"เปลี่ยนแปลง" },
{ word:"amount", meaning:"จำนวน" },
{ word:"anger", meaning:"ความโกรธ" },
{ word:"angle", meaning:"มุม" },
{ word:"anniversary", meaning:"วันครบรอบ" },
{ word:"annual", meaning:"ประจำปี" },
{ word:"anxious", meaning:"กังวล" },
{ word:"apparent", meaning:"ชัดเจน" },
{ word:"apparently", meaning:"เห็นได้ชัดว่า" },
{ word:"appeal", meaning:"ดึงดูด, อุทธรณ์" },
{ word:"approach", meaning:"วิธี, เข้าใกล้" },
{ word:"appropriate", meaning:"เหมาะสม" },
{ word:"approval", meaning:"การอนุมัติ" },
{ word:"approve", meaning:"อนุมัติ" },
{ word:"arise", meaning:"เกิดขึ้น" },
{ word:"armed", meaning:"ติดอาวุธ" },
{ word:"arms", meaning:"อาวุธ" },
{ word:"artificial", meaning:"เทียม, สังเคราะห์" },
{ word:"artistic", meaning:"ทางศิลปะ" },
{ word:"ashamed", meaning:"ละอายใจ" },
{ word:"aspect", meaning:"แง่มุม" },
{ word:"assess", meaning:"ประเมิน" },
{ word:"assessment", meaning:"การประเมิน" },
{ word:"associate", meaning:"เชื่อมโยง" },
{ word:"associated", meaning:"ที่เกี่ยวข้อง" },
{ word:"association", meaning:"สมาคม, ความเกี่ยวข้อง" },
{ word:"assume", meaning:"สมมติ" },
{ word:"attempt", meaning:"พยายาม" },
{ word:"back", meaning:"ด้านหลัง, สนับสนุน" },
{ word:"bacteria", meaning:"แบคทีเรีย" },
{ word:"bar", meaning:"แท่ง, บาร์" },
{ word:"barrier", meaning:"อุปสรรค" },
{ word:"basically", meaning:"โดยพื้นฐาน" },
{ word:"battle", meaning:"การต่อสู้" },
{ word:"bear", meaning:"รับมือ, ทน" },
{ word:"beat", meaning:"เอาชนะ" },
{ word:"beg", meaning:"ขอร้อง" },
{ word:"being", meaning:"สิ่งมีชีวิต" },
{ word:"bent", meaning:"โค้งงอ" },
{ word:"bet", meaning:"พนัน" },
{ word:"beyond", meaning:"เกินกว่า" },
{ word:"bill", meaning:"บิล, ร่างกฎหมาย" },
{ word:"bitter", meaning:"ขม, ขมขื่น" },
{ word:"blame", meaning:"ตำหนิ" },
{ word:"blind", meaning:"ตาบอด" },
{ word:"bond", meaning:"พันธะ" },
{ word:"border", meaning:"ชายแดน" },
{ word:"breast", meaning:"หน้าอก" },
{ word:"brief", meaning:"สั้น, กระชับ" },
{ word:"broad", meaning:"กว้าง" },
{ word:"broadcast", meaning:"ออกอากาศ" },
{ word:"budget", meaning:"งบประมาณ" },
{ word:"bullet", meaning:"กระสุน" },
{ word:"bunch", meaning:"กลุ่ม, พวง" },
{ word:"burn", meaning:"เผาไหม้" },
{ word:"bush", meaning:"พุ่มไม้" },
{ word:"but", meaning:"แต่" },
{ word:"cable", meaning:"สายเคเบิล" },
{ word:"calculate", meaning:"คำนวณ" },
{ word:"cancel", meaning:"ยกเลิก" },
{ word:"cancer", meaning:"มะเร็ง" },
{ word:"capable", meaning:"สามารถ" },
{ word:"capacity", meaning:"ความจุ, ศักยภาพ" },
{ word:"capture", meaning:"จับกุม" },
{ word:"cast", meaning:"โยน, คัดเลือก" },
{ word:"catch", meaning:"จับ" },
{ word:"cell", meaning:"เซลล์" },
{ word:"chain", meaning:"โซ่" },
{ word:"chair", meaning:"เก้าอี้" },
{ word:"chairman", meaning:"ประธาน" },
{ word:"challenge", meaning:"ความท้าทาย" },
{ word:"characteristic", meaning:"ลักษณะเฉพาะ" },
{ word:"chart", meaning:"แผนภูมิ" },
{ word:"chief", meaning:"หัวหน้า" },
{ word:"circumstance", meaning:"สถานการณ์" },
{ word:"cite", meaning:"อ้างอิง" },
{ word:"citizen", meaning:"พลเมือง" },
{ word:"civil", meaning:"พลเรือน" },
{ word:"classic", meaning:"คลาสสิก" },
{ word:"close1", meaning:"ใกล้" },
{ word:"closely", meaning:"อย่างใกล้ชิด" },
{ word:"collapse", meaning:"พังทลาย" },
{ word:"combination", meaning:"การผสม" },
{ word:"comfort", meaning:"ความสบาย" },
{ word:"command", meaning:"คำสั่ง" },
{ word:"commission", meaning:"คณะกรรมการ, ค่าคอมมิชชัน" },
{ word:"commitment", meaning:"ความมุ่งมั่น" },
{ word:"committee", meaning:"คณะกรรมการ" },
{ word:"commonly", meaning:"โดยทั่วไป" },
{ word:"complex", meaning:"ซับซ้อน" },
{ word:"complicated", meaning:"ยุ่งยาก" },
{ word:"component", meaning:"ส่วนประกอบ" },
{ word:"concentration", meaning:"สมาธิ" },
{ word:"concept", meaning:"แนวคิด" },
{ word:"concern", meaning:"ความกังวล, เกี่ยวข้อง" },
{ word:"concerned", meaning:"กังวล, เกี่ยวข้อง" },
{ word:"conduct", meaning:"ดำเนินการ" },
{ word:"confidence", meaning:"ความมั่นใจ" },
{ word:"conflict", meaning:"ความขัดแย้ง" },
{ word:"confusing", meaning:"สับสน" },
{ word:"conscious", meaning:"มีสติ" },
{ word:"conservative", meaning:"อนุรักษ์นิยม" },
{ word:"consideration", meaning:"การพิจารณา" },
{ word:"consistent", meaning:"สม่ำเสมอ" },
{ word:"constant", meaning:"คงที่" },
{ word:"constantly", meaning:"ตลอดเวลา" },
{ word:"construct", meaning:"ก่อสร้าง" },
{ word:"construction", meaning:"การก่อสร้าง" },
{ word:"contemporary", meaning:"ร่วมสมัย" },
{ word:"contest", meaning:"การแข่งขัน" },
{ word:"contract", meaning:"สัญญา" },
{ word:"contribute", meaning:"มีส่วนร่วม" },
{ word:"contribution", meaning:"การมีส่วนร่วม" },
{ word:"convert", meaning:"เปลี่ยนแปลง" },
{ word:"convinced", meaning:"เชื่อมั่น" },
{ word:"core", meaning:"แกนกลาง" },
{ word:"corporate", meaning:"องค์กร" },
{ word:"council", meaning:"สภา" },
{ word:"county", meaning:"เขตการปกครอง" },
{ word:"courage", meaning:"ความกล้าหาญ" },
{ word:"crash", meaning:"ชน, พัง" },
{ word:"creation", meaning:"การสร้าง" },
{ word:"creature", meaning:"สิ่งมีชีวิต" },
{ word:"credit", meaning:"เครดิต, ความน่าเชื่อถือ" },
{ word:"crew", meaning:"ลูกเรือ, ทีมงาน" },
{ word:"crisis", meaning:"วิกฤต" },
{ word:"criterion", meaning:"เกณฑ์" },
{ word:"critic", meaning:"นักวิจารณ์" },
{ word:"critical", meaning:"สำคัญ, วิกฤต" },
{ word:"criticism", meaning:"การวิจารณ์" },
{ word:"criticize", meaning:"วิจารณ์" },
{ word:"crop", meaning:"พืชผล" },
{ word:"crucial", meaning:"สำคัญยิ่ง" },
{ word:"cry", meaning:"ร้องไห้" },
{ word:"cure", meaning:"รักษา" },
{ word:"current", meaning:"ปัจจุบัน" },
{ word:"curve", meaning:"เส้นโค้ง" },
{ word:"curved", meaning:"โค้ง" },
{ word:"date", meaning:"วันที่" },
{ word:"debate", meaning:"การโต้วาที" },
{ word:"debt", meaning:"หนี้" },
{ word:"decent", meaning:"ดีพอใช้" },
{ word:"declare", meaning:"ประกาศ" },
{ word:"decline", meaning:"ลดลง" },
{ word:"decoration", meaning:"การตกแต่ง" },
{ word:"decrease", meaning:"ลดลง" },
{ word:"deeply", meaning:"อย่างลึกซึ้ง" },
{ word:"defeat", meaning:"เอาชนะ" },
{ word:"defence", meaning:"การป้องกัน" },
{ word:"defend", meaning:"ปกป้อง" },
{ word:"delay", meaning:"ล่าช้า" },
{ word:"deliberate", meaning:"จงใจ" },
{ word:"deliberately", meaning:"โดยเจตนา" },
{ word:"delight", meaning:"ความยินดี" },
{ word:"delighted", meaning:"ยินดีมาก" },
{ word:"delivery", meaning:"การส่งมอบ" },
{ word:"demand", meaning:"ความต้องการ" },
{ word:"demonstrate", meaning:"แสดงให้เห็น" },
{ word:"deny", meaning:"ปฏิเสธ" },
{ word:"depressed", meaning:"หดหู่" },
{ word:"depressing", meaning:"น่าหดหู่" },
{ word:"depth", meaning:"ความลึก" },
{ word:"desert", meaning:"ทะเลทราย" },
{ word:"deserve", meaning:"สมควรได้รับ" },
{ word:"desire", meaning:"ความปรารถนา" },
{ word:"desperate", meaning:"สิ้นหวัง" },
{ word:"detail", meaning:"รายละเอียด" },
{ word:"detailed", meaning:"ละเอียด" },
{ word:"detect", meaning:"ตรวจพบ" },
{ word:"dig", meaning:"ขุด" },
{ word:"disc", meaning:"แผ่นดิสก์" },
{ word:"discipline", meaning:"วินัย" },
{ word:"discount", meaning:"ส่วนลด" },
{ word:"dishonest", meaning:"ไม่ซื่อสัตย์" },
{ word:"dismiss", meaning:"ไล่ออก, ยกเลิก" },
{ word:"display", meaning:"แสดง" },
{ word:"distribute", meaning:"แจกจ่าย" },
{ word:"distribution", meaning:"การแจกจ่าย" },
{ word:"district", meaning:"เขต" },
{ word:"divide", meaning:"แบ่ง" },
{ word:"division", meaning:"การแบ่ง" },
{ word:"document", meaning:"เอกสาร" },
{ word:"domestic", meaning:"ภายในประเทศ" },
{ word:"dominate", meaning:"ครอบงำ" },
{ word:"downwards", meaning:"ลงล่าง" },
{ word:"dozen", meaning:"หนึ่งโหล" },
{ word:"draft", meaning:"ร่าง" },
{ word:"drag", meaning:"ลาก" },
{ word:"dramatic", meaning:"น่าทึ่ง" },
{ word:"edit", meaning:"แก้ไข" },
{ word:"edition", meaning:"ฉบับ" },
{ word:"efficient", meaning:"มีประสิทธิภาพ" },
{ word:"elderly", meaning:"สูงอายุ" },
{ word:"elect", meaning:"เลือกตั้ง" },
{ word:"elsewhere", meaning:"ที่อื่น" },
{ word:"emerge", meaning:"ปรากฏ" },
{ word:"emotional", meaning:"ทางอารมณ์" },
{ word:"emphasis", meaning:"การเน้น" },
{ word:"emphasize", meaning:"เน้น" },
{ word:"enable", meaning:"ทำให้สามารถ" },
{ word:"encounter", meaning:"พบเจอ" },
{ word:"engage", meaning:"มีส่วนร่วม" },
{ word:"enhance", meaning:"เพิ่มพูน" },
{ word:"enquiry", meaning:"การสอบถาม" },
{ word:"ensure", meaning:"รับประกัน" },
{ word:"enthusiasm", meaning:"ความกระตือรือร้น" },
{ word:"enthusiastic", meaning:"กระตือรือร้น" },
{ word:"entire", meaning:"ทั้งหมด" },
{ word:"entirely", meaning:"โดยสิ้นเชิง" },
{ word:"equal", meaning:"เท่ากัน" },
{ word:"establish", meaning:"ก่อตั้ง" },
{ word:"estate", meaning:"ทรัพย์สิน" },
{ word:"estimate", meaning:"ประมาณการ" },
{ word:"ethical", meaning:"มีจริยธรรม" },
{ word:"evaluate", meaning:"ประเมิน" },
{ word:"even", meaning:"แม้แต่, ยิ่ง" },
{ word:"evil", meaning:"ชั่วร้าย" },
{ word:"examination", meaning:"การสอบ, การตรวจ" },
{ word:"excuse", meaning:"ข้ออ้าง, ให้อภัย" },
{ word:"executive", meaning:"ผู้บริหาร" },
{ word:"existence", meaning:"การมีอยู่" },
{ word:"expectation", meaning:"ความคาดหวัง" },
{ word:"expense", meaning:"ค่าใช้จ่าย" },
{ word:"exploration", meaning:"การสำรวจ" },
{ word:"expose", meaning:"เปิดเผย" },
{ word:"extend", meaning:"ขยาย" },
{ word:"extent", meaning:"ขอบเขต" },
{ word:"external", meaning:"ภายนอก" },
{ word:"extraordinary", meaning:"พิเศษ, ไม่ธรรมดา" },
{ word:"extreme", meaning:"รุนแรง, สุดขั้ว" },
{ word:"facility", meaning:"สิ่งอำนวยความสะดวก" },
{ word:"failure", meaning:"ความล้มเหลว" },
{ word:"faith", meaning:"ศรัทธา" },
{ word:"fault", meaning:"ความผิด" },
{ word:"favour", meaning:"ความโปรดปราน" },
{ word:"feather", meaning:"ขนนก" },
{ word:"fee", meaning:"ค่าธรรมเนียม" },
{ word:"feed", meaning:"ให้อาหาร" },
{ word:"feedback", meaning:"ข้อเสนอแนะ" },
{ word:"feel", meaning:"รู้สึก" },
{ word:"fellow", meaning:"เพื่อนร่วม" },
{ word:"figure", meaning:"ตัวเลข, รูปร่าง" },
{ word:"file", meaning:"ไฟล์, เอกสาร" },
{ word:"finance", meaning:"การเงิน" },
{ word:"finding", meaning:"ผลการค้นพบ" },
{ word:"firm", meaning:"บริษัท, มั่นคง" },
{ word:"fix", meaning:"ซ่อม, แก้ไข" },
{ word:"flame", meaning:"เปลวไฟ" },
{ word:"flash", meaning:"แสงวาบ" },
{ word:"flexible", meaning:"ยืดหยุ่น" },
{ word:"float", meaning:"ลอย" },
{ word:"fold", meaning:"พับ" },
{ word:"folding", meaning:"พับได้" },
{ word:"following", meaning:"ถัดไป, ต่อไปนี้" },
{ word:"forgive", meaning:"ให้อภัย" },
{ word:"former", meaning:"อดีต" },
{ word:"fortune", meaning:"โชคชะตา, โชคลาภ" },
{ word:"forward", meaning:"ข้างหน้า" },
{ word:"found", meaning:"ก่อตั้ง" },
{ word:"free", meaning:"อิสระ, ฟรี" },
{ word:"freedom", meaning:"เสรีภาพ" },
{ word:"frequency", meaning:"ความถี่" },
{ word:"fuel", meaning:"เชื้อเพลิง" },
{ word:"fully", meaning:"อย่างเต็มที่" },
{ word:"function", meaning:"หน้าที่, การทำงาน" },
{ word:"fund", meaning:"กองทุน" },
{ word:"fundamental", meaning:"พื้นฐาน" },
{ word:"funding", meaning:"เงินทุน" },
{ word:"furthermore", meaning:"นอกจากนี้" },
{ word:"gain", meaning:"ได้รับ, เพิ่มขึ้น" },
{ word:"gang", meaning:"แก๊ง" },
{ word:"generate", meaning:"สร้าง, ก่อให้เกิด" },
{ word:"genre", meaning:"ประเภท" },
{ word:"govern", meaning:"ปกครอง" },
{ word:"grab", meaning:"คว้า" },
{ word:"grade", meaning:"เกรด, ระดับ" },
{ word:"gradually", meaning:"ค่อยๆ" },
{ word:"grand", meaning:"ยิ่งใหญ่" },
{ word:"grant", meaning:"มอบ, อนุมัติ" },
{ word:"guarantee", meaning:"รับประกัน" },
{ word:"handle", meaning:"จัดการ" },
{ word:"harm", meaning:"อันตราย" },
{ word:"harmful", meaning:"เป็นอันตราย" },
{ word:"hearing", meaning:"การได้ยิน" },
{ word:"heaven", meaning:"สวรรค์" },
{ word:"heel", meaning:"ส้นเท้า" },
{ word:"hell", meaning:"นรก" },
{ word:"hesitate", meaning:"ลังเล" },
{ word:"high", meaning:"สูง" },
{ word:"hire", meaning:"จ้าง" },
{ word:"hold", meaning:"ถือ, จัดขึ้น" },
{ word:"hollow", meaning:"กลวง" },
{ word:"holy", meaning:"ศักดิ์สิทธิ์" },
{ word:"honour", meaning:"เกียรติ, ให้เกียรติ" },
{ word:"host", meaning:"เจ้าภาพ" },
{ word:"house", meaning:"บ้าน" },
{ word:"household", meaning:"ครัวเรือน" },
{ word:"housing", meaning:"ที่อยู่อาศัย" },
{ word:"humorous", meaning:"ตลก" },
{ word:"humour", meaning:"อารมณ์ขัน" },
{ word:"hunt", meaning:"ล่า" },
{ word:"hunting", meaning:"การล่า" },
{ word:"hurt", meaning:"เจ็บ, ทำร้าย" },
{ word:"ideal", meaning:"อุดมคติ, เหมาะสม" },
{ word:"illustrate", meaning:"อธิบาย, แสดง" },
{ word:"illustration", meaning:"ภาพประกอบ" },
{ word:"imagination", meaning:"จินตนาการ" },
{ word:"impatient", meaning:"ใจร้อน" },
{ word:"imply", meaning:"สื่อความ, บอกเป็นนัย" },
{ word:"impose", meaning:"กำหนด, บังคับ" },
{ word:"impress", meaning:"สร้างความประทับใจ" },
{ word:"impressed", meaning:"ประทับใจ" },
{ word:"inch", meaning:"นิ้ว" },
{ word:"incident", meaning:"เหตุการณ์" },
{ word:"income", meaning:"รายได้" },
{ word:"increasingly", meaning:"มากขึ้นเรื่อยๆ" },
{ word:"industrial", meaning:"อุตสาหกรรม" },
{ word:"infection", meaning:"การติดเชื้อ" },
{ word:"inform", meaning:"แจ้ง" },
{ word:"initial", meaning:"เริ่มต้น" },
{ word:"initially", meaning:"ในตอนแรก" },
{ word:"initiative", meaning:"ความคิดริเริ่ม" },
{ word:"inner", meaning:"ภายใน" },
{ word:"insight", meaning:"ความเข้าใจลึกซึ้ง" },
{ word:"insist", meaning:"ยืนกราน" },
{ word:"inspire", meaning:"สร้างแรงบันดาลใจ" },
{ word:"install", meaning:"ติดตั้ง" },
{ word:"instance", meaning:"กรณี, ตัวอย่าง" },
{ word:"institute", meaning:"สถาบัน" },
{ word:"institution", meaning:"องค์กร, สถาบัน" },
{ word:"insurance", meaning:"ประกันภัย" },
{ word:"intended", meaning:"ที่ตั้งใจไว้" },
{ word:"intense", meaning:"รุนแรง, เข้มข้น" },
{ word:"internal", meaning:"ภายใน" },
{ word:"interpret", meaning:"ตีความ" },
{ word:"interrupt", meaning:"ขัดจังหวะ" },
{ word:"investigation", meaning:"การสอบสวน" },
{ word:"investment", meaning:"การลงทุน" },
{ word:"issue", meaning:"ประเด็น, ปัญหา" },
{ word:"joy", meaning:"ความสุข" },
{ word:"judgement", meaning:"การตัดสิน" },
{ word:"junior", meaning:"ระดับต้น" },
{ word:"justice", meaning:"ความยุติธรรม" },
{ word:"justify", meaning:"ให้เหตุผล" },
{ word:"labour", meaning:"แรงงาน" },
{ word:"landscape", meaning:"ภูมิทัศน์" },
{ word:"largely", meaning:"ส่วนใหญ่" },
{ word:"latest", meaning:"ล่าสุด" },
{ word:"launch", meaning:"เปิดตัว" },
{ word:"leadership", meaning:"ภาวะผู้นำ" },
{ word:"league", meaning:"ลีก, สมาคม" },
{ word:"lean", meaning:"เอน, โน้ม" },
{ word:"leave", meaning:"ออกจาก, ทิ้งไว้" },
{ word:"level", meaning:"ระดับ" },
{ word:"licence", meaning:"ใบอนุญาต" },
{ word:"limited", meaning:"จำกัด" },
{ word:"line", meaning:"เส้น, สาย" },
{ word:"lively", meaning:"มีชีวิตชีวา" },
{ word:"load", meaning:"บรรทุก, ภาระ" },
{ word:"loan", meaning:"เงินกู้" },
{ word:"logical", meaning:"มีเหตุผล" },
{ word:"long-term", meaning:"ระยะยาว" },
{ word:"loose", meaning:"หลวม" },
{ word:"lord", meaning:"ท่านลอร์ด" },
{ word:"low", meaning:"ต่ำ" },
{ word:"lower", meaning:"ต่ำกว่า, ลดลง" },
{ word:"lung", meaning:"ปอด" },
{ word:"maintain", meaning:"รักษา, คงไว้" },
{ word:"majority", meaning:"คนส่วนใหญ่" },
{ word:"make", meaning:"ทำ, สร้าง" },
{ word:"map", meaning:"แผนที่" },
{ word:"mass", meaning:"มวล, จำนวนมาก" },
{ word:"massive", meaning:"มหาศาล" },
{ word:"master", meaning:"เชี่ยวชาญ, นาย" },
{ word:"matching", meaning:"เข้ากัน" },
{ word:"material", meaning:"วัสดุ" },
{ word:"maximum", meaning:"สูงสุด" },
{ word:"means", meaning:"วิธีการ" },
{ word:"measurement", meaning:"การวัด" },
{ word:"medium", meaning:"สื่อกลาง, ปานกลาง" },
{ word:"melt", meaning:"ละลาย" },
{ word:"military", meaning:"ทหาร" },
{ word:"mineral", meaning:"แร่ธาตุ" },
{ word:"minimum", meaning:"ต่ำสุด" },
{ word:"minister", meaning:"รัฐมนตรี" },
{ word:"minor", meaning:"เล็กน้อย" },
{ word:"minority", meaning:"ชนกลุ่มน้อย" },
{ word:"mission", meaning:"ภารกิจ" },
{ word:"mistake", meaning:"ความผิดพลาด" },
{ word:"mixed", meaning:"ผสมกัน" },
{ word:"model", meaning:"แบบจำลอง, แบบ" },
{ word:"modify", meaning:"ปรับเปลี่ยน" },
{ word:"monitor", meaning:"ติดตาม, ตรวจสอบ" },
{ word:"moral", meaning:"ศีลธรรม" },
{ word:"motor", meaning:"มอเตอร์" },
{ word:"mount", meaning:"ติดตั้ง, ขึ้น" },
{ word:"multiple", meaning:"หลาย, หลายเท่า" },
{ word:"multiply", meaning:"คูณ, เพิ่มขึ้น" },
{ word:"mysterious", meaning:"ลึกลับ" },
{ word:"narrow", meaning:"แคบ" },
{ word:"national", meaning:"แห่งชาติ" },
{ word:"neat", meaning:"เรียบร้อย" },
{ word:"negative", meaning:"เชิงลบ" },
{ word:"nerve", meaning:"เส้นประสาท" },
{ word:"nevertheless", meaning:"อย่างไรก็ตาม" },
{ word:"nightmare", meaning:"ฝันร้าย" },
{ word:"notion", meaning:"แนวคิด" },
{ word:"numerous", meaning:"มากมาย" },
{ word:"obey", meaning:"เชื่อฟัง" },
{ word:"object", meaning:"วัตถุ, คัดค้าน" },
{ word:"objective", meaning:"วัตถุประสงค์" },
{ word:"obligation", meaning:"หน้าที่" },
{ word:"observation", meaning:"การสังเกต" },
{ word:"observe", meaning:"สังเกต" },
{ word:"obtain", meaning:"ได้รับ" },
{ word:"occasionally", meaning:"เป็นครั้งคราว" },
{ word:"offence", meaning:"ความผิด, การรุก" },
{ word:"offend", meaning:"ทำให้ขุ่นเคือง" },
{ word:"offensive", meaning:"ก้าวร้าว, น่ารังเกียจ" },
{ word:"official", meaning:"ทางการ, เจ้าหน้าที่" },
{ word:"opening", meaning:"การเปิด, ช่องว่าง" },
{ word:"operate", meaning:"ดำเนินงาน" },
{ word:"opponent", meaning:"คู่ต่อสู้" },
{ word:"oppose", meaning:"คัดค้าน" },
{ word:"opposed", meaning:"คัดค้าน, ตรงข้าม" },
{ word:"opposition", meaning:"ฝ่ายค้าน, การคัดค้าน" },
{ word:"organ", meaning:"อวัยวะ" },
{ word:"origin", meaning:"ต้นกำเนิด" },
{ word:"otherwise", meaning:"มิฉะนั้น" },
{ word:"outcome", meaning:"ผลลัพธ์" },
{ word:"outer", meaning:"ภายนอก" },
{ word:"outline", meaning:"โครงร่าง" },
{ word:"overall", meaning:"โดยรวม" },
{ word:"owe", meaning:"เป็นหนี้" },
{ word:"pace", meaning:"จังหวะ, ความเร็ว" },
{ word:"package", meaning:"พัสดุ, ชุด" },
{ word:"panel", meaning:"คณะกรรมการ" },
{ word:"parliament", meaning:"รัฐสภา" },
{ word:"participant", meaning:"ผู้เข้าร่วม" },
{ word:"partly", meaning:"บางส่วน" },
{ word:"passage", meaning:"ทางผ่าน, ตอน" },
{ word:"patient", meaning:"ผู้ป่วย, อดทน" },
{ word:"pension1", meaning:"เงินบำนาญ" },
{ word:"permanent", meaning:"ถาวร" },
{ word:"permit", meaning:"อนุญาต, ใบอนุญาต" },
{ word:"perspective", meaning:"มุมมอง" },
{ word:"phase", meaning:"ระยะ, ขั้นตอน" },
{ word:"phenomenon", meaning:"ปรากฏการณ์" },
{ word:"philosophy", meaning:"ปรัชญา" },
{ word:"pick", meaning:"เลือก, หยิบ" },
{ word:"picture", meaning:"รูปภาพ" },
{ word:"pile", meaning:"กอง" },
{ word:"pitch", meaning:"ขว้าง, สนาม" },
{ word:"plain", meaning:"ธรรมดา, ชัดเจน" },
{ word:"plot", meaning:"โครงเรื่อง, แผนการ" },
{ word:"plus1", meaning:"บวก, เพิ่ม" },
{ word:"pointed", meaning:"แหลม" },
{ word:"popularity", meaning:"ความนิยม" },
{ word:"pose", meaning:"ก่อให้เกิด, โพสท่า" },
{ word:"position", meaning:"ตำแหน่ง" },
{ word:"positive", meaning:"เชิงบวก" },
{ word:"possess", meaning:"ครอบครอง" },
{ word:"potential", meaning:"ศักยภาพ" },
{ word:"power", meaning:"พลัง, อำนาจ" },
{ word:"praise", meaning:"ชมเชย" },
{ word:"pregnant", meaning:"ตั้งครรภ์" },
{ word:"preparation", meaning:"การเตรียม" },
{ word:"presence", meaning:"การปรากฏตัว" },
{ word:"preserve", meaning:"รักษาไว้" },
{ word:"price", meaning:"ราคา" },
{ word:"prime", meaning:"สำคัญที่สุด" },
{ word:"principle", meaning:"หลักการ" },
{ word:"print", meaning:"พิมพ์" },
{ word:"priority", meaning:"ลำดับความสำคัญ" },
{ word:"privacy", meaning:"ความเป็นส่วนตัว" },
{ word:"procedure", meaning:"ขั้นตอน" },
{ word:"process", meaning:"กระบวนการ" },
{ word:"produce", meaning:"ผลิต" },
{ word:"professional", meaning:"มืออาชีพ" },
{ word:"progress", meaning:"ความก้าวหน้า" },
{ word:"project", meaning:"โครงการ" },
{ word:"proof", meaning:"หลักฐาน" },
{ word:"proposal", meaning:"ข้อเสนอ" },
{ word:"propose", meaning:"เสนอ" },
{ word:"prospect", meaning:"โอกาส" },
{ word:"protection", meaning:"การป้องกัน" },
{ word:"psychologist", meaning:"นักจิตวิทยา" },
{ word:"psychology", meaning:"จิตวิทยา" },
{ word:"publication", meaning:"สิ่งพิมพ์" },
{ word:"pupil", meaning:"นักเรียน" },
{ word:"purchase", meaning:"ซื้อ" },
{ word:"pure", meaning:"บริสุทธิ์" },
{ word:"pursue", meaning:"ไล่ตาม, มุ่งมั่น" },
{ word:"range", meaning:"ช่วง, ขอบเขต" },
{ word:"rank", meaning:"อันดับ" },
{ word:"rapid", meaning:"รวดเร็ว" },
{ word:"rapidly", meaning:"อย่างรวดเร็ว" },
{ word:"rate", meaning:"อัตรา" },
{ word:"raw", meaning:"ดิบ" },
{ word:"reach", meaning:"ไปถึง" },
{ word:"realistic", meaning:"สมจริง" },
{ word:"reasonable", meaning:"สมเหตุสมผล" },
{ word:"recall", meaning:"นึกออก, เรียกคืน" },
{ word:"recover", meaning:"ฟื้นตัว" },
{ word:"reduction", meaning:"การลดลง" },
{ word:"regard", meaning:"มองว่า, ความนับถือ" },
{ word:"regional", meaning:"ระดับภูมิภาค" },
{ word:"register", meaning:"ลงทะเบียน" },
{ word:"regret", meaning:"เสียใจ, เสียดาย" },
{ word:"regulation", meaning:"กฎระเบียบ" },
{ word:"relatively", meaning:"ค่อนข้าง" },
{ word:"relevant", meaning:"เกี่ยวข้อง" },
{ word:"relief", meaning:"ความโล่งใจ" },
{ word:"rely", meaning:"พึ่งพา" },
{ word:"remark", meaning:"ข้อสังเกต, กล่าว" },
{ word:"representative", meaning:"ตัวแทน" },
{ word:"reputation", meaning:"ชื่อเสียง" },
{ word:"requirement", meaning:"ข้อกำหนด" },
{ word:"rescue", meaning:"ช่วยเหลือ" },
{ word:"reserve", meaning:"สำรอง, จอง" },
{ word:"resident", meaning:"ผู้อยู่อาศัย" },
{ word:"resist", meaning:"ต่อต้าน" },
{ word:"resolve", meaning:"แก้ไข, ตัดสินใจ" },
{ word:"resort", meaning:"รีสอร์ต, ทางเลือก" },
{ word:"retain", meaning:"รักษาไว้" },
{ word:"reveal", meaning:"เปิดเผย" },
{ word:"revolution", meaning:"การปฏิวัติ" },
{ word:"reward", meaning:"รางวัล" },
{ word:"rhythm", meaning:"จังหวะ" },
{ word:"rid", meaning:"กำจัด" },
{ word:"root", meaning:"ราก" },
{ word:"round", meaning:"กลม, รอบ" },
{ word:"routine", meaning:"กิจวัตร" },
{ word:"rub", meaning:"ถู" },
{ word:"rubber", meaning:"ยาง" },
{ word:"rural", meaning:"ชนบท" },
{ word:"rush", meaning:"เร่งรีบ" },
{ word:"sample", meaning:"ตัวอย่าง" },
{ word:"satellite", meaning:"ดาวเทียม" },
{ word:"satisfied", meaning:"พอใจ" },
{ word:"satisfy", meaning:"ทำให้พอใจ" },
{ word:"saving", meaning:"การออม" },
{ word:"scale", meaning:"ขนาด, มาตราส่วน" },
{ word:"schedule", meaning:"ตารางเวลา" },
{ word:"scheme", meaning:"แผนการ" },
{ word:"scream", meaning:"กรีดร้อง" },
{ word:"screen", meaning:"หน้าจอ" },
{ word:"seat", meaning:"ที่นั่ง" },
{ word:"sector", meaning:"ภาคส่วน" },
{ word:"secure", meaning:"ปลอดภัย, ทำให้มั่นคง" },
{ word:"seek", meaning:"แสวงหา" },
{ word:"select", meaning:"เลือก" },
{ word:"selection", meaning:"การเลือก" },
{ word:"self", meaning:"ตนเอง" },
{ word:"senior", meaning:"อาวุโส" },
{ word:"sense", meaning:"ความรู้สึก, สำนึก" },
{ word:"sensitive", meaning:"อ่อนไหว" },
{ word:"sentence", meaning:"ประโยค, คำพิพากษา" },
{ word:"sequence", meaning:"ลำดับ" },
{ word:"session", meaning:"ช่วงเวลา, สมัยประชุม" },
{ word:"settle", meaning:"ตั้งถิ่นฐาน, จัดการ" },
{ word:"severe", meaning:"รุนแรง" },
{ word:"shade", meaning:"ร่มเงา" },
{ word:"shadow", meaning:"เงา" },
{ word:"shallow", meaning:"ตื้น" },
{ word:"shame", meaning:"ความอับอาย" },
{ word:"shape", meaning:"รูปร่าง" },
{ word:"shelter", meaning:"ที่พักพิง" },
{ word:"shift", meaning:"เปลี่ยน, กะงาน" },
{ word:"ship", meaning:"เรือ" },
{ word:"shock", meaning:"ตกใจ, แรงกระแทก" },
{ word:"shocked", meaning:"ตกใจ" },
{ word:"shooting", meaning:"การยิง" },
{ word:"shot", meaning:"การยิง, นัดยิง" },
{ word:"significant", meaning:"สำคัญ" },
{ word:"significantly", meaning:"อย่างมาก" },
{ word:"silence", meaning:"ความเงียบ" },
{ word:"silk", meaning:"ไหม" },
{ word:"sincere", meaning:"จริงใจ" },
{ word:"slave", meaning:"ทาส" },
{ word:"slide", meaning:"ลื่น, สไลด์" },
{ word:"slight", meaning:"เล็กน้อย" },
{ word:"slip", meaning:"ลื่น, หลุด" },
{ word:"slope", meaning:"ทางลาด" },
{ word:"solar", meaning:"เกี่ยวกับดวงอาทิตย์" },
{ word:"somewhat", meaning:"ค่อนข้าง" },
{ word:"soul", meaning:"จิตวิญญาณ" },
{ word:"specialist", meaning:"ผู้เชี่ยวชาญ" },
{ word:"species", meaning:"สายพันธุ์" },
{ word:"speed", meaning:"ความเร็ว" },
{ word:"spiritual", meaning:"ทางจิตวิญญาณ" },
{ word:"split", meaning:"แยก, แบ่ง" },
{ word:"sponsor", meaning:"ผู้สนับสนุน" },
{ word:"spot", meaning:"จุด, สังเกตเห็น" },
{ word:"spread", meaning:"กระจาย" },
{ word:"stable", meaning:"มั่นคง" },
{ word:"stage", meaning:"ขั้นตอน, เวที" },
{ word:"stand", meaning:"ยืน" },
{ word:"stare", meaning:"จ้องมอง" },
{ word:"status", meaning:"สถานะ" },
{ word:"steady", meaning:"มั่นคง, สม่ำเสมอ" },
{ word:"steel", meaning:"เหล็กกล้า" },
{ word:"steep", meaning:"ชัน" },
{ word:"step", meaning:"ก้าว, ขั้นตอน" },
{ word:"sticky", meaning:"เหนียว" },
{ word:"stiff", meaning:"แข็ง, ตึง" },
{ word:"stock", meaning:"หุ้น, สินค้าคงคลัง" },
{ word:"stream", meaning:"ลำธาร, กระแส" },
{ word:"stretch", meaning:"ยืด" },
{ word:"strict", meaning:"เข้มงวด" },
{ word:"strike", meaning:"ตี, นัดหยุดงาน" },
{ word:"structure", meaning:"โครงสร้าง" },
{ word:"struggle", meaning:"ดิ้นรน" },
{ word:"stuff", meaning:"สิ่งของ" },
{ word:"subject", meaning:"หัวข้อ, วิชา" },
{ word:"submit", meaning:"ส่ง, ยื่น" },
{ word:"sum", meaning:"ผลรวม" },
{ word:"surgery", meaning:"การผ่าตัด" },
{ word:"surround", meaning:"ล้อมรอบ" },
{ word:"surrounding", meaning:"โดยรอบ" },
{ word:"survey", meaning:"การสำรวจ" },
{ word:"suspect", meaning:"สงสัย, ผู้ต้องสงสัย" },
{ word:"swear", meaning:"สาบาน" },
{ word:"sweep", meaning:"กวาด" },
{ word:"switch", meaning:"สวิตช์, เปลี่ยน" },
{ word:"sympathy", meaning:"ความเห็นใจ" },
{ word:"tale", meaning:"เรื่องเล่า" },
{ word:"tank", meaning:"ถัง, รถถัง" },
{ word:"target", meaning:"เป้าหมาย" },
{ word:"tear1", meaning:"น้ำตา" },
{ word:"tear2", meaning:"ฉีกขาด" },
{ word:"temporary", meaning:"ชั่วคราว" },
{ word:"term", meaning:"คำศัพท์, ระยะเวลา" },
{ word:"therapy", meaning:"การบำบัด" },
{ word:"threat", meaning:"ภัยคุกคาม" },
{ word:"threaten", meaning:"คุกคาม" },
{ word:"thus", meaning:"ดังนั้น" },
{ word:"time", meaning:"เวลา" },
{ word:"title", meaning:"ชื่อเรื่อง, ตำแหน่ง" },
{ word:"tone", meaning:"น้ำเสียง" },
{ word:"tough", meaning:"ยาก, แข็งแกร่ง" },
{ word:"track", meaning:"เส้นทาง, ติดตาม" },
{ word:"transfer", meaning:"โอน, ย้าย" },
{ word:"transform", meaning:"เปลี่ยนแปลง" },
{ word:"transition", meaning:"การเปลี่ยนผ่าน" },
{ word:"trial", meaning:"การทดลอง, การพิจารณาคดี" },
{ word:"trip", meaning:"การเดินทาง" },
{ word:"tropical", meaning:"เขตร้อน" },
{ word:"trouble", meaning:"ปัญหา" },
{ word:"truly", meaning:"อย่างแท้จริง" },
{ word:"trust", meaning:"เชื่อใจ, ความไว้วางใจ" },
{ word:"try", meaning:"พยายาม" },
{ word:"tune", meaning:"ทำนอง, ปรับแต่ง" },
{ word:"tunnel", meaning:"อุโมงค์" },
{ word:"ultimately", meaning:"ท้ายที่สุด" },
{ word:"unconscious", meaning:"หมดสติ" },
{ word:"unexpected", meaning:"ไม่คาดคิด" },
{ word:"unique", meaning:"เป็นเอกลักษณ์" },
{ word:"universe", meaning:"จักรวาล" },
{ word:"unknown", meaning:"ไม่รู้จัก" },
{ word:"upper", meaning:"ด้านบน" },
{ word:"upwards", meaning:"ขึ้นข้างบน" },
{ word:"urban", meaning:"ในเมือง" },
{ word:"urge", meaning:"กระตุ้น, เร่งเร้า" },
{ word:"value", meaning:"คุณค่า, มูลค่า" },
{ word:"vary", meaning:"แตกต่าง, เปลี่ยนแปลง" },
{ word:"vast", meaning:"กว้างใหญ่" },
{ word:"venue", meaning:"สถานที่จัดงาน" },
{ word:"very", meaning:"มาก" },
{ word:"via", meaning:"ผ่าน" },
{ word:"victory", meaning:"ชัยชนะ" },
{ word:"violence", meaning:"ความรุนแรง" },
{ word:"virtual", meaning:"เสมือนจริง" },
{ word:"vision", meaning:"วิสัยทัศน์, การมองเห็น" },
{ word:"visual", meaning:"เกี่ยวกับการมองเห็น" },
{ word:"vital", meaning:"สำคัญยิ่ง" },
{ word:"vitamin", meaning:"วิตามิน" },
{ word:"volume", meaning:"ปริมาตร, ระดับเสียง" },
{ word:"wage", meaning:"ค่าจ้าง" },
{ word:"way", meaning:"ทาง, วิธี" },
{ word:"weakness", meaning:"จุดอ่อน" },
{ word:"wealth", meaning:"ความมั่งคั่ง" },
{ word:"wealthy", meaning:"มั่งคั่ง" },
{ word:"whereas", meaning:"ในขณะที่" },
{ word:"wherever", meaning:"ไม่ว่าที่ไหน" },
{ word:"whisper", meaning:"กระซิบ" },
{ word:"whom", meaning:"ผู้ซึ่ง" },
{ word:"widely", meaning:"อย่างกว้างขวาง" },
{ word:"wildlife", meaning:"สัตว์ป่า" },
{ word:"willing", meaning:"เต็มใจ" },
{ word:"wind2", meaning:"ลม" },
{ word:"wire", meaning:"ลวด, สายไฟ" },
{ word:"wise", meaning:"ฉลาด" },
{ word:"witness", meaning:"พยาน" },
{ word:"worse", meaning:"แย่กว่า" },
{ word:"worst", meaning:"แย่ที่สุด" },
{ word:"worth", meaning:"คุ้มค่า" },
{ word:"wound", meaning:"บาดแผล" },
{ word:"wrap", meaning:"ห่อ" },
{ word:"wrong", meaning:"ผิด" },
{ word:"yet", meaning:"ยัง, แต่" },
{ word:"zone", meaning:"เขต" }
];