window.Vonouns2 = [
  { word: "거리", meaning: "ถนน, ทาง" },
  { word: "거실", meaning: "ห้องรับแขก" },
  { word: "거울", meaning: "กระจก" },
  { word: "거절", meaning: "การปฏิเสธ" },
  { word: "거짓말", meaning: "การพูดโกหก, คำพูดโกหก" },
  { word: "걱정", meaning: "ความกังวล, ความเป็นห่วง" },
  { word: "건강", meaning: "สุขภาพ" },
  { word: "건너편", meaning: "ฝั่งตรงข้าม" },
  { word: "건물", meaning: "ตึก" },
  { word: "검사", meaning: "การตรวจ" },
  { word: "검은색", meaning: "สีดำ" },
  { word: "것", meaning: "สิ่ง, ของ" },
  { word: "게임", meaning: "เกม" },
  { word: "겨울", meaning: "ฤดูหนาว" },
  { word: "결과", meaning: "ผล, ผลลัพธ์" },
  { word: "결석", meaning: "การขาด, การขาดเรียน, การไม่เข้าร่วม" },
  { word: "결심", meaning: "การตัดสินใจ, การตกลงใจ" },
  { word: "결정", meaning: "การตัดสินใจ, การตัดสิน" },
  { word: "결혼", meaning: "การแต่งงาน" },
  { word: "결혼식", meaning: "งานแต่งงาน" },
  { word: "경기", meaning: "การแข่งขัน" },
  { word: "경찰", meaning: "ตำรวจ" },
  { word: "경치", meaning: "ทิวทัศน์, วิว" },
  { word: "경험", meaning: "ประสบการณ์" },
  { word: "계단", meaning: "บันได" },
];